"""Compatibility imports for the canonical material model owner."""

from witwin.channel.materials.models import (  # noqa: F401
    DIELECTRIC_MODEL_ID,
    DISPERSIVE_MODEL_ID,
    GEOMETRY_MODE_IDS,
    MATERIAL_ABI_VERSION,
    PEC_EFFECTIVE_SIGMA_E,
    PEC_MODEL_ID,
    PHYSICAL_SURFACE_MODEL_ID,
    _VACUUM_PERMITTIVITY,
    DebyeModel,
    Dielectric,
    DispersiveMaterial,
    ITUMaterial,
    Layer,
    LossyDielectric,
    PerfectConductor,
    PhaseScreen,
    PhysicalSurface,
    Roughness,
    SurfaceAssignment,
    TabulatedPermittivity,
    _finite,
    _nonnegative,
    _positive,
    _unit_interval,
    dataclass,
    effective_sigma_e,
    math,
)
