#include "drjit_common.h"
#include <monitors/field/reflection_grid/bind.h>

#include <monitors/field/reflection_grid/reflection_grid.h>

void register_reflection_grid_bindings(nb::module_ &m) {
    m.def(
        "reflection_grid_forward_raw",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            std::uintptr_t coord_0,
            std::uintptr_t coord_1,
            std::uintptr_t active,
            std::uintptr_t ray_origin_x,
            std::uintptr_t ray_origin_y,
            std::uintptr_t ray_origin_z,
            std::uintptr_t ray_dir_x,
            std::uintptr_t ray_dir_y,
            std::uintptr_t ray_dir_z,
            std::uintptr_t blocker_dist,
            std::uintptr_t prev_refl_p_x,
            std::uintptr_t prev_refl_p_y,
            std::uintptr_t prev_refl_p_z,
            std::uintptr_t prev_refl_n_x,
            std::uintptr_t prev_refl_n_y,
            std::uintptr_t prev_refl_n_z,
            std::uintptr_t prev_tx_x,
            std::uintptr_t prev_tx_y,
            std::uintptr_t prev_tx_z,
            std::uintptr_t prev_weight_re,
            std::uintptr_t prev_weight_im,
            std::uintptr_t prev_pol_x_re,
            std::uintptr_t prev_pol_x_im,
            std::uintptr_t prev_pol_y_re,
            std::uintptr_t prev_pol_y_im,
            std::uintptr_t prev_pol_z_re,
            std::uintptr_t prev_pol_z_im,
            std::uintptr_t prev_prim_idx,
            int validate_paths,
            int has_mesh_data,
            std::uintptr_t tri_v0_x,
            std::uintptr_t tri_v0_y,
            std::uintptr_t tri_v0_z,
            std::uintptr_t tri_v1_x,
            std::uintptr_t tri_v1_y,
            std::uintptr_t tri_v1_z,
            std::uintptr_t tri_v2_x,
            std::uintptr_t tri_v2_y,
            std::uintptr_t tri_v2_z,
            std::uintptr_t tri_group_size,
            std::uintptr_t tri_group_members,
            int max_group_size,
            float wavelength,
            float k,
            int n_rays,
            std::uintptr_t out_field_re,
            std::uintptr_t out_field_im,
            std::uintptr_t out_count,
            std::uintptr_t out_pol_x_re,
            std::uintptr_t out_pol_x_im,
            std::uintptr_t out_pol_y_re,
            std::uintptr_t out_pol_y_im,
            std::uintptr_t out_pol_z_re,
            std::uintptr_t out_pol_z_im
        ) {
            witwin::channel::native_ext::reflection_grid_forward(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                ptr<const float>(coord_0),
                ptr<const float>(coord_1),
                ptr<const int>(active),
                ptr<const float>(ray_origin_x),
                ptr<const float>(ray_origin_y),
                ptr<const float>(ray_origin_z),
                ptr<const float>(ray_dir_x),
                ptr<const float>(ray_dir_y),
                ptr<const float>(ray_dir_z),
                ptr<const float>(blocker_dist),
                ptr<const float>(prev_refl_p_x),
                ptr<const float>(prev_refl_p_y),
                ptr<const float>(prev_refl_p_z),
                ptr<const float>(prev_refl_n_x),
                ptr<const float>(prev_refl_n_y),
                ptr<const float>(prev_refl_n_z),
                ptr<const float>(prev_tx_x),
                ptr<const float>(prev_tx_y),
                ptr<const float>(prev_tx_z),
                ptr<const float>(prev_weight_re),
                ptr<const float>(prev_weight_im),
                ptr<const float>(prev_pol_x_re),
                ptr<const float>(prev_pol_x_im),
                ptr<const float>(prev_pol_y_re),
                ptr<const float>(prev_pol_y_im),
                ptr<const float>(prev_pol_z_re),
                ptr<const float>(prev_pol_z_im),
                ptr<const int>(prev_prim_idx),
                validate_paths,
                has_mesh_data,
                ptr<const float>(tri_v0_x),
                ptr<const float>(tri_v0_y),
                ptr<const float>(tri_v0_z),
                ptr<const float>(tri_v1_x),
                ptr<const float>(tri_v1_y),
                ptr<const float>(tri_v1_z),
                ptr<const float>(tri_v2_x),
                ptr<const float>(tri_v2_y),
                ptr<const float>(tri_v2_z),
                ptr<const int>(tri_group_size),
                ptr<const int>(tri_group_members),
                max_group_size,
                wavelength,
                k,
                n_rays,
                ptr_mut<float>(out_field_re),
                ptr_mut<float>(out_field_im),
                ptr_mut<float>(out_count),
                ptr_mut<float>(out_pol_x_re),
                ptr_mut<float>(out_pol_x_im),
                ptr_mut<float>(out_pol_y_re),
                ptr_mut<float>(out_pol_y_im),
                ptr_mut<float>(out_pol_z_re),
                ptr_mut<float>(out_pol_z_im)
            );
        },
        "Launch reflection-grid forward accumulation kernel."
    );

    m.def(
        "reflection_grid_jvp_raw",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            std::uintptr_t coord_0,
            std::uintptr_t coord_1,
            std::uintptr_t active,
            std::uintptr_t ray_origin_x,
            std::uintptr_t ray_origin_y,
            std::uintptr_t ray_origin_z,
            std::uintptr_t ray_dir_x,
            std::uintptr_t ray_dir_y,
            std::uintptr_t ray_dir_z,
            std::uintptr_t blocker_dist,
            std::uintptr_t prev_refl_p_x,
            std::uintptr_t prev_refl_p_y,
            std::uintptr_t prev_refl_p_z,
            std::uintptr_t prev_refl_n_x,
            std::uintptr_t prev_refl_n_y,
            std::uintptr_t prev_refl_n_z,
            std::uintptr_t prev_tx_x,
            std::uintptr_t prev_tx_y,
            std::uintptr_t prev_tx_z,
            std::uintptr_t prev_weight_re,
            std::uintptr_t prev_weight_im,
            std::uintptr_t prev_pol_x_re,
            std::uintptr_t prev_pol_x_im,
            std::uintptr_t prev_pol_y_re,
            std::uintptr_t prev_pol_y_im,
            std::uintptr_t prev_pol_z_re,
            std::uintptr_t prev_pol_z_im,
            std::uintptr_t prev_prim_idx,
            int validate_paths,
            int has_mesh_data,
            std::uintptr_t tri_v0_x,
            std::uintptr_t tri_v0_y,
            std::uintptr_t tri_v0_z,
            std::uintptr_t tri_v1_x,
            std::uintptr_t tri_v1_y,
            std::uintptr_t tri_v1_z,
            std::uintptr_t tri_v2_x,
            std::uintptr_t tri_v2_y,
            std::uintptr_t tri_v2_z,
            std::uintptr_t tri_group_size,
            std::uintptr_t tri_group_members,
            int max_group_size,
            std::uintptr_t t_prev_refl_p_x,
            std::uintptr_t t_prev_refl_p_y,
            std::uintptr_t t_prev_refl_p_z,
            std::uintptr_t t_prev_refl_n_x,
            std::uintptr_t t_prev_refl_n_y,
            std::uintptr_t t_prev_refl_n_z,
            std::uintptr_t t_prev_tx_x,
            std::uintptr_t t_prev_tx_y,
            std::uintptr_t t_prev_tx_z,
            std::uintptr_t t_prev_weight_re,
            std::uintptr_t t_prev_weight_im,
            std::uintptr_t t_prev_pol_x_re,
            std::uintptr_t t_prev_pol_x_im,
            std::uintptr_t t_prev_pol_y_re,
            std::uintptr_t t_prev_pol_y_im,
            std::uintptr_t t_prev_pol_z_re,
            std::uintptr_t t_prev_pol_z_im,
            float wavelength,
            float k,
            int n_rays,
            std::uintptr_t out_field_re,
            std::uintptr_t out_field_im,
            std::uintptr_t out_pol_x_re,
            std::uintptr_t out_pol_x_im,
            std::uintptr_t out_pol_y_re,
            std::uintptr_t out_pol_y_im,
            std::uintptr_t out_pol_z_re,
            std::uintptr_t out_pol_z_im
        ) {
            witwin::channel::native_ext::reflection_grid_jvp(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                ptr<const float>(coord_0),
                ptr<const float>(coord_1),
                ptr<const int>(active),
                ptr<const float>(ray_origin_x),
                ptr<const float>(ray_origin_y),
                ptr<const float>(ray_origin_z),
                ptr<const float>(ray_dir_x),
                ptr<const float>(ray_dir_y),
                ptr<const float>(ray_dir_z),
                ptr<const float>(blocker_dist),
                ptr<const float>(prev_refl_p_x),
                ptr<const float>(prev_refl_p_y),
                ptr<const float>(prev_refl_p_z),
                ptr<const float>(prev_refl_n_x),
                ptr<const float>(prev_refl_n_y),
                ptr<const float>(prev_refl_n_z),
                ptr<const float>(prev_tx_x),
                ptr<const float>(prev_tx_y),
                ptr<const float>(prev_tx_z),
                ptr<const float>(prev_weight_re),
                ptr<const float>(prev_weight_im),
                ptr<const float>(prev_pol_x_re),
                ptr<const float>(prev_pol_x_im),
                ptr<const float>(prev_pol_y_re),
                ptr<const float>(prev_pol_y_im),
                ptr<const float>(prev_pol_z_re),
                ptr<const float>(prev_pol_z_im),
                ptr<const int>(prev_prim_idx),
                validate_paths,
                has_mesh_data,
                ptr<const float>(tri_v0_x),
                ptr<const float>(tri_v0_y),
                ptr<const float>(tri_v0_z),
                ptr<const float>(tri_v1_x),
                ptr<const float>(tri_v1_y),
                ptr<const float>(tri_v1_z),
                ptr<const float>(tri_v2_x),
                ptr<const float>(tri_v2_y),
                ptr<const float>(tri_v2_z),
                ptr<const int>(tri_group_size),
                ptr<const int>(tri_group_members),
                max_group_size,
                ptr<const float>(t_prev_refl_p_x),
                ptr<const float>(t_prev_refl_p_y),
                ptr<const float>(t_prev_refl_p_z),
                ptr<const float>(t_prev_refl_n_x),
                ptr<const float>(t_prev_refl_n_y),
                ptr<const float>(t_prev_refl_n_z),
                ptr<const float>(t_prev_tx_x),
                ptr<const float>(t_prev_tx_y),
                ptr<const float>(t_prev_tx_z),
                ptr<const float>(t_prev_weight_re),
                ptr<const float>(t_prev_weight_im),
                ptr<const float>(t_prev_pol_x_re),
                ptr<const float>(t_prev_pol_x_im),
                ptr<const float>(t_prev_pol_y_re),
                ptr<const float>(t_prev_pol_y_im),
                ptr<const float>(t_prev_pol_z_re),
                ptr<const float>(t_prev_pol_z_im),
                wavelength,
                k,
                n_rays,
                ptr_mut<float>(out_field_re),
                ptr_mut<float>(out_field_im),
                ptr_mut<float>(out_pol_x_re),
                ptr_mut<float>(out_pol_x_im),
                ptr_mut<float>(out_pol_y_re),
                ptr_mut<float>(out_pol_y_im),
                ptr_mut<float>(out_pol_z_re),
                ptr_mut<float>(out_pol_z_im)
            );
        },
        "Launch reflection-grid JVP kernel."
    );

    m.def(
        "reflection_grid_backward_raw",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            std::uintptr_t coord_0,
            std::uintptr_t coord_1,
            std::uintptr_t active,
            std::uintptr_t ray_origin_x,
            std::uintptr_t ray_origin_y,
            std::uintptr_t ray_origin_z,
            std::uintptr_t ray_dir_x,
            std::uintptr_t ray_dir_y,
            std::uintptr_t ray_dir_z,
            std::uintptr_t blocker_dist,
            std::uintptr_t prev_refl_p_x,
            std::uintptr_t prev_refl_p_y,
            std::uintptr_t prev_refl_p_z,
            std::uintptr_t prev_refl_n_x,
            std::uintptr_t prev_refl_n_y,
            std::uintptr_t prev_refl_n_z,
            std::uintptr_t prev_tx_x,
            std::uintptr_t prev_tx_y,
            std::uintptr_t prev_tx_z,
            std::uintptr_t prev_weight_re,
            std::uintptr_t prev_weight_im,
            std::uintptr_t prev_pol_x_re,
            std::uintptr_t prev_pol_x_im,
            std::uintptr_t prev_pol_y_re,
            std::uintptr_t prev_pol_y_im,
            std::uintptr_t prev_pol_z_re,
            std::uintptr_t prev_pol_z_im,
            std::uintptr_t prev_prim_idx,
            int validate_paths,
            int has_mesh_data,
            std::uintptr_t tri_v0_x,
            std::uintptr_t tri_v0_y,
            std::uintptr_t tri_v0_z,
            std::uintptr_t tri_v1_x,
            std::uintptr_t tri_v1_y,
            std::uintptr_t tri_v1_z,
            std::uintptr_t tri_v2_x,
            std::uintptr_t tri_v2_y,
            std::uintptr_t tri_v2_z,
            std::uintptr_t tri_group_size,
            std::uintptr_t tri_group_members,
            int max_group_size,
            float wavelength,
            float k,
            int n_rays,
            std::uintptr_t grad_field_re,
            std::uintptr_t grad_field_im,
            std::uintptr_t grad_pol_x_re,
            std::uintptr_t grad_pol_x_im,
            std::uintptr_t grad_pol_y_re,
            std::uintptr_t grad_pol_y_im,
            std::uintptr_t grad_pol_z_re,
            std::uintptr_t grad_pol_z_im,
            std::uintptr_t grad_prev_refl_p_x,
            std::uintptr_t grad_prev_refl_p_y,
            std::uintptr_t grad_prev_refl_p_z,
            std::uintptr_t grad_prev_refl_n_x,
            std::uintptr_t grad_prev_refl_n_y,
            std::uintptr_t grad_prev_refl_n_z,
            std::uintptr_t grad_prev_tx_x,
            std::uintptr_t grad_prev_tx_y,
            std::uintptr_t grad_prev_tx_z,
            std::uintptr_t grad_prev_weight_re,
            std::uintptr_t grad_prev_weight_im,
            std::uintptr_t grad_prev_pol_x_re,
            std::uintptr_t grad_prev_pol_x_im,
            std::uintptr_t grad_prev_pol_y_re,
            std::uintptr_t grad_prev_pol_y_im,
            std::uintptr_t grad_prev_pol_z_re,
            std::uintptr_t grad_prev_pol_z_im
        ) {
            witwin::channel::native_ext::reflection_grid_backward(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                ptr<const float>(coord_0),
                ptr<const float>(coord_1),
                ptr<const int>(active),
                ptr<const float>(ray_origin_x),
                ptr<const float>(ray_origin_y),
                ptr<const float>(ray_origin_z),
                ptr<const float>(ray_dir_x),
                ptr<const float>(ray_dir_y),
                ptr<const float>(ray_dir_z),
                ptr<const float>(blocker_dist),
                ptr<const float>(prev_refl_p_x),
                ptr<const float>(prev_refl_p_y),
                ptr<const float>(prev_refl_p_z),
                ptr<const float>(prev_refl_n_x),
                ptr<const float>(prev_refl_n_y),
                ptr<const float>(prev_refl_n_z),
                ptr<const float>(prev_tx_x),
                ptr<const float>(prev_tx_y),
                ptr<const float>(prev_tx_z),
                ptr<const float>(prev_weight_re),
                ptr<const float>(prev_weight_im),
                ptr<const float>(prev_pol_x_re),
                ptr<const float>(prev_pol_x_im),
                ptr<const float>(prev_pol_y_re),
                ptr<const float>(prev_pol_y_im),
                ptr<const float>(prev_pol_z_re),
                ptr<const float>(prev_pol_z_im),
                ptr<const int>(prev_prim_idx),
                validate_paths,
                has_mesh_data,
                ptr<const float>(tri_v0_x),
                ptr<const float>(tri_v0_y),
                ptr<const float>(tri_v0_z),
                ptr<const float>(tri_v1_x),
                ptr<const float>(tri_v1_y),
                ptr<const float>(tri_v1_z),
                ptr<const float>(tri_v2_x),
                ptr<const float>(tri_v2_y),
                ptr<const float>(tri_v2_z),
                ptr<const int>(tri_group_size),
                ptr<const int>(tri_group_members),
                max_group_size,
                wavelength,
                k,
                n_rays,
                ptr<const float>(grad_field_re),
                ptr<const float>(grad_field_im),
                ptr<const float>(grad_pol_x_re),
                ptr<const float>(grad_pol_x_im),
                ptr<const float>(grad_pol_y_re),
                ptr<const float>(grad_pol_y_im),
                ptr<const float>(grad_pol_z_re),
                ptr<const float>(grad_pol_z_im),
                ptr_mut<float>(grad_prev_refl_p_x),
                ptr_mut<float>(grad_prev_refl_p_y),
                ptr_mut<float>(grad_prev_refl_p_z),
                ptr_mut<float>(grad_prev_refl_n_x),
                ptr_mut<float>(grad_prev_refl_n_y),
                ptr_mut<float>(grad_prev_refl_n_z),
                ptr_mut<float>(grad_prev_tx_x),
                ptr_mut<float>(grad_prev_tx_y),
                ptr_mut<float>(grad_prev_tx_z),
                ptr_mut<float>(grad_prev_weight_re),
                ptr_mut<float>(grad_prev_weight_im),
                ptr_mut<float>(grad_prev_pol_x_re),
                ptr_mut<float>(grad_prev_pol_x_im),
                ptr_mut<float>(grad_prev_pol_y_re),
                ptr_mut<float>(grad_prev_pol_y_im),
                ptr_mut<float>(grad_prev_pol_z_re),
                ptr_mut<float>(grad_prev_pol_z_im)
            );
        },
        "Launch reflection-grid backward kernel."
    );

    m.def(
        "reflection_grid_forward_arrays",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            const DiffFloat &coord_0,
            const DiffFloat &coord_1,
            const Int32 &active,
            const DiffFloat &ray_origin_x,
            const DiffFloat &ray_origin_y,
            const DiffFloat &ray_origin_z,
            const DiffFloat &ray_dir_x,
            const DiffFloat &ray_dir_y,
            const DiffFloat &ray_dir_z,
            const DiffFloat &blocker_dist,
            const DiffFloat &prev_refl_p_x,
            const DiffFloat &prev_refl_p_y,
            const DiffFloat &prev_refl_p_z,
            const DiffFloat &prev_refl_n_x,
            const DiffFloat &prev_refl_n_y,
            const DiffFloat &prev_refl_n_z,
            const DiffFloat &prev_tx_x,
            const DiffFloat &prev_tx_y,
            const DiffFloat &prev_tx_z,
            const DiffFloat &prev_weight_re,
            const DiffFloat &prev_weight_im,
            const DiffFloat &prev_pol_x_re,
            const DiffFloat &prev_pol_x_im,
            const DiffFloat &prev_pol_y_re,
            const DiffFloat &prev_pol_y_im,
            const DiffFloat &prev_pol_z_re,
            const DiffFloat &prev_pol_z_im,
            const Int32 &prev_prim_idx,
            int validate_paths,
            int has_mesh_data,
            const DiffFloat &tri_v0_x,
            const DiffFloat &tri_v0_y,
            const DiffFloat &tri_v0_z,
            const DiffFloat &tri_v1_x,
            const DiffFloat &tri_v1_y,
            const DiffFloat &tri_v1_z,
            const DiffFloat &tri_v2_x,
            const DiffFloat &tri_v2_y,
            const DiffFloat &tri_v2_z,
            const Int32 &tri_group_size,
            const Int32 &tri_group_members,
            int max_group_size,
            float wavelength,
            float k,
            int n_rays
        ) {
            size_t n_rx = static_cast<size_t>(n_coord_0) * static_cast<size_t>(n_coord_1);
            DiffFloat out_field_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_field_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_count = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_pol_x_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_pol_x_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_pol_y_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_pol_y_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_pol_z_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_pol_z_im = drjit::zeros<DiffFloat>(n_rx);
            drjit::eval(
                coord_0,
                coord_1,
                active,
                ray_origin_x,
                ray_origin_y,
                ray_origin_z,
                ray_dir_x,
                ray_dir_y,
                ray_dir_z,
                blocker_dist,
                prev_refl_p_x,
                prev_refl_p_y,
                prev_refl_p_z,
                prev_refl_n_x,
                prev_refl_n_y,
                prev_refl_n_z,
                prev_tx_x,
                prev_tx_y,
                prev_tx_z,
                prev_weight_re,
                prev_weight_im,
                prev_pol_x_re,
                prev_pol_x_im,
                prev_pol_y_re,
                prev_pol_y_im,
                prev_pol_z_re,
                prev_pol_z_im,
                prev_prim_idx,
                out_field_re,
                out_field_im,
                out_count,
                out_pol_x_re,
                out_pol_x_im,
                out_pol_y_re,
                out_pol_y_im,
                out_pol_z_re,
                out_pol_z_im
            );
            if (has_mesh_data) {
                drjit::eval(
                    tri_v0_x, tri_v0_y, tri_v0_z,
                    tri_v1_x, tri_v1_y, tri_v1_z,
                    tri_v2_x, tri_v2_y, tri_v2_z,
                    tri_group_size, tri_group_members
                );
            }

            witwin::channel::native_ext::reflection_grid_forward(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                drjit_data_ptr(coord_0),
                drjit_data_ptr(coord_1),
                drjit_data_ptr(active),
                drjit_data_ptr(ray_origin_x),
                drjit_data_ptr(ray_origin_y),
                drjit_data_ptr(ray_origin_z),
                drjit_data_ptr(ray_dir_x),
                drjit_data_ptr(ray_dir_y),
                drjit_data_ptr(ray_dir_z),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(prev_refl_p_x),
                drjit_data_ptr(prev_refl_p_y),
                drjit_data_ptr(prev_refl_p_z),
                drjit_data_ptr(prev_refl_n_x),
                drjit_data_ptr(prev_refl_n_y),
                drjit_data_ptr(prev_refl_n_z),
                drjit_data_ptr(prev_tx_x),
                drjit_data_ptr(prev_tx_y),
                drjit_data_ptr(prev_tx_z),
                drjit_data_ptr(prev_weight_re),
                drjit_data_ptr(prev_weight_im),
                drjit_data_ptr(prev_pol_x_re),
                drjit_data_ptr(prev_pol_x_im),
                drjit_data_ptr(prev_pol_y_re),
                drjit_data_ptr(prev_pol_y_im),
                drjit_data_ptr(prev_pol_z_re),
                drjit_data_ptr(prev_pol_z_im),
                drjit_data_ptr(prev_prim_idx),
                validate_paths,
                has_mesh_data,
                has_mesh_data ? drjit_data_ptr(tri_v0_x) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v0_y) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v0_z) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v1_x) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v1_y) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v1_z) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v2_x) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v2_y) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v2_z) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_group_size) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_group_members) : nullptr,
                max_group_size,
                wavelength,
                k,
                n_rays,
                drjit_data_ptr_mut(out_field_re),
                drjit_data_ptr_mut(out_field_im),
                drjit_data_ptr_mut(out_count),
                drjit_data_ptr_mut(out_pol_x_re),
                drjit_data_ptr_mut(out_pol_x_im),
                drjit_data_ptr_mut(out_pol_y_re),
                drjit_data_ptr_mut(out_pol_y_im),
                drjit_data_ptr_mut(out_pol_z_re),
                drjit_data_ptr_mut(out_pol_z_im)
            );
            return nb::make_tuple(
                out_field_re,
                out_field_im,
                out_count,
                out_pol_x_re,
                out_pol_x_im,
                out_pol_y_re,
                out_pol_y_im,
                out_pol_z_re,
                out_pol_z_im
            );
        },
        "Launch reflection-grid forward kernel with zero-copy Dr.Jit arrays."
    );

    m.def(
        "reflection_grid_jvp_arrays",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            const DiffFloat &coord_0,
            const DiffFloat &coord_1,
            const Int32 &active,
            const DiffFloat &ray_origin_x,
            const DiffFloat &ray_origin_y,
            const DiffFloat &ray_origin_z,
            const DiffFloat &ray_dir_x,
            const DiffFloat &ray_dir_y,
            const DiffFloat &ray_dir_z,
            const DiffFloat &blocker_dist,
            const DiffFloat &prev_refl_p_x,
            const DiffFloat &prev_refl_p_y,
            const DiffFloat &prev_refl_p_z,
            const DiffFloat &prev_refl_n_x,
            const DiffFloat &prev_refl_n_y,
            const DiffFloat &prev_refl_n_z,
            const DiffFloat &prev_tx_x,
            const DiffFloat &prev_tx_y,
            const DiffFloat &prev_tx_z,
            const DiffFloat &prev_weight_re,
            const DiffFloat &prev_weight_im,
            const DiffFloat &prev_pol_x_re,
            const DiffFloat &prev_pol_x_im,
            const DiffFloat &prev_pol_y_re,
            const DiffFloat &prev_pol_y_im,
            const DiffFloat &prev_pol_z_re,
            const DiffFloat &prev_pol_z_im,
            const Int32 &prev_prim_idx,
            int validate_paths,
            int has_mesh_data,
            const DiffFloat &tri_v0_x,
            const DiffFloat &tri_v0_y,
            const DiffFloat &tri_v0_z,
            const DiffFloat &tri_v1_x,
            const DiffFloat &tri_v1_y,
            const DiffFloat &tri_v1_z,
            const DiffFloat &tri_v2_x,
            const DiffFloat &tri_v2_y,
            const DiffFloat &tri_v2_z,
            const Int32 &tri_group_size,
            const Int32 &tri_group_members,
            int max_group_size,
            const DiffFloat &t_prev_refl_p_x,
            const DiffFloat &t_prev_refl_p_y,
            const DiffFloat &t_prev_refl_p_z,
            const DiffFloat &t_prev_refl_n_x,
            const DiffFloat &t_prev_refl_n_y,
            const DiffFloat &t_prev_refl_n_z,
            const DiffFloat &t_prev_tx_x,
            const DiffFloat &t_prev_tx_y,
            const DiffFloat &t_prev_tx_z,
            const DiffFloat &t_prev_weight_re,
            const DiffFloat &t_prev_weight_im,
            const DiffFloat &t_prev_pol_x_re,
            const DiffFloat &t_prev_pol_x_im,
            const DiffFloat &t_prev_pol_y_re,
            const DiffFloat &t_prev_pol_y_im,
            const DiffFloat &t_prev_pol_z_re,
            const DiffFloat &t_prev_pol_z_im,
            float wavelength,
            float k,
            int n_rays
        ) {
            size_t n_rx = static_cast<size_t>(n_coord_0) * static_cast<size_t>(n_coord_1);
            DiffFloat out_field_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_field_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_pol_x_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_pol_x_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_pol_y_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_pol_y_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_pol_z_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_pol_z_im = drjit::zeros<DiffFloat>(n_rx);
            drjit::eval(
                coord_0,
                coord_1,
                active,
                ray_origin_x,
                ray_origin_y,
                ray_origin_z,
                ray_dir_x,
                ray_dir_y,
                ray_dir_z,
                blocker_dist,
                prev_refl_p_x,
                prev_refl_p_y,
                prev_refl_p_z,
                prev_refl_n_x,
                prev_refl_n_y,
                prev_refl_n_z,
                prev_tx_x,
                prev_tx_y,
                prev_tx_z,
                prev_weight_re,
                prev_weight_im,
                prev_pol_x_re,
                prev_pol_x_im,
                prev_pol_y_re,
                prev_pol_y_im,
                prev_pol_z_re,
                prev_pol_z_im,
                prev_prim_idx,
                t_prev_refl_p_x,
                t_prev_refl_p_y,
                t_prev_refl_p_z,
                t_prev_refl_n_x,
                t_prev_refl_n_y,
                t_prev_refl_n_z,
                t_prev_tx_x,
                t_prev_tx_y,
                t_prev_tx_z,
                t_prev_weight_re,
                t_prev_weight_im,
                t_prev_pol_x_re,
                t_prev_pol_x_im,
                t_prev_pol_y_re,
                t_prev_pol_y_im,
                t_prev_pol_z_re,
                t_prev_pol_z_im,
                out_field_re,
                out_field_im,
                out_pol_x_re,
                out_pol_x_im,
                out_pol_y_re,
                out_pol_y_im,
                out_pol_z_re,
                out_pol_z_im
            );
            if (has_mesh_data) {
                drjit::eval(
                    tri_v0_x, tri_v0_y, tri_v0_z,
                    tri_v1_x, tri_v1_y, tri_v1_z,
                    tri_v2_x, tri_v2_y, tri_v2_z,
                    tri_group_size, tri_group_members
                );
            }

            witwin::channel::native_ext::reflection_grid_jvp(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                drjit_data_ptr(coord_0),
                drjit_data_ptr(coord_1),
                drjit_data_ptr(active),
                drjit_data_ptr(ray_origin_x),
                drjit_data_ptr(ray_origin_y),
                drjit_data_ptr(ray_origin_z),
                drjit_data_ptr(ray_dir_x),
                drjit_data_ptr(ray_dir_y),
                drjit_data_ptr(ray_dir_z),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(prev_refl_p_x),
                drjit_data_ptr(prev_refl_p_y),
                drjit_data_ptr(prev_refl_p_z),
                drjit_data_ptr(prev_refl_n_x),
                drjit_data_ptr(prev_refl_n_y),
                drjit_data_ptr(prev_refl_n_z),
                drjit_data_ptr(prev_tx_x),
                drjit_data_ptr(prev_tx_y),
                drjit_data_ptr(prev_tx_z),
                drjit_data_ptr(prev_weight_re),
                drjit_data_ptr(prev_weight_im),
                drjit_data_ptr(prev_pol_x_re),
                drjit_data_ptr(prev_pol_x_im),
                drjit_data_ptr(prev_pol_y_re),
                drjit_data_ptr(prev_pol_y_im),
                drjit_data_ptr(prev_pol_z_re),
                drjit_data_ptr(prev_pol_z_im),
                drjit_data_ptr(prev_prim_idx),
                validate_paths,
                has_mesh_data,
                has_mesh_data ? drjit_data_ptr(tri_v0_x) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v0_y) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v0_z) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v1_x) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v1_y) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v1_z) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v2_x) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v2_y) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v2_z) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_group_size) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_group_members) : nullptr,
                max_group_size,
                drjit_data_ptr(t_prev_refl_p_x),
                drjit_data_ptr(t_prev_refl_p_y),
                drjit_data_ptr(t_prev_refl_p_z),
                drjit_data_ptr(t_prev_refl_n_x),
                drjit_data_ptr(t_prev_refl_n_y),
                drjit_data_ptr(t_prev_refl_n_z),
                drjit_data_ptr(t_prev_tx_x),
                drjit_data_ptr(t_prev_tx_y),
                drjit_data_ptr(t_prev_tx_z),
                drjit_data_ptr(t_prev_weight_re),
                drjit_data_ptr(t_prev_weight_im),
                drjit_data_ptr(t_prev_pol_x_re),
                drjit_data_ptr(t_prev_pol_x_im),
                drjit_data_ptr(t_prev_pol_y_re),
                drjit_data_ptr(t_prev_pol_y_im),
                drjit_data_ptr(t_prev_pol_z_re),
                drjit_data_ptr(t_prev_pol_z_im),
                wavelength,
                k,
                n_rays,
                drjit_data_ptr_mut(out_field_re),
                drjit_data_ptr_mut(out_field_im),
                drjit_data_ptr_mut(out_pol_x_re),
                drjit_data_ptr_mut(out_pol_x_im),
                drjit_data_ptr_mut(out_pol_y_re),
                drjit_data_ptr_mut(out_pol_y_im),
                drjit_data_ptr_mut(out_pol_z_re),
                drjit_data_ptr_mut(out_pol_z_im)
            );
            return nb::make_tuple(
                out_field_re,
                out_field_im,
                out_pol_x_re,
                out_pol_x_im,
                out_pol_y_re,
                out_pol_y_im,
                out_pol_z_re,
                out_pol_z_im
            );
        },
        "Launch reflection-grid JVP kernel with zero-copy Dr.Jit arrays."
    );

    m.def(
        "reflection_grid_backward_arrays",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            const DiffFloat &coord_0,
            const DiffFloat &coord_1,
            const Int32 &active,
            const DiffFloat &ray_origin_x,
            const DiffFloat &ray_origin_y,
            const DiffFloat &ray_origin_z,
            const DiffFloat &ray_dir_x,
            const DiffFloat &ray_dir_y,
            const DiffFloat &ray_dir_z,
            const DiffFloat &blocker_dist,
            const DiffFloat &prev_refl_p_x,
            const DiffFloat &prev_refl_p_y,
            const DiffFloat &prev_refl_p_z,
            const DiffFloat &prev_refl_n_x,
            const DiffFloat &prev_refl_n_y,
            const DiffFloat &prev_refl_n_z,
            const DiffFloat &prev_tx_x,
            const DiffFloat &prev_tx_y,
            const DiffFloat &prev_tx_z,
            const DiffFloat &prev_weight_re,
            const DiffFloat &prev_weight_im,
            const DiffFloat &prev_pol_x_re,
            const DiffFloat &prev_pol_x_im,
            const DiffFloat &prev_pol_y_re,
            const DiffFloat &prev_pol_y_im,
            const DiffFloat &prev_pol_z_re,
            const DiffFloat &prev_pol_z_im,
            const Int32 &prev_prim_idx,
            int validate_paths,
            int has_mesh_data,
            const DiffFloat &tri_v0_x,
            const DiffFloat &tri_v0_y,
            const DiffFloat &tri_v0_z,
            const DiffFloat &tri_v1_x,
            const DiffFloat &tri_v1_y,
            const DiffFloat &tri_v1_z,
            const DiffFloat &tri_v2_x,
            const DiffFloat &tri_v2_y,
            const DiffFloat &tri_v2_z,
            const Int32 &tri_group_size,
            const Int32 &tri_group_members,
            int max_group_size,
            float wavelength,
            float k,
            int n_rays,
            const DiffFloat &grad_field_re,
            const DiffFloat &grad_field_im,
            const DiffFloat &grad_pol_x_re,
            const DiffFloat &grad_pol_x_im,
            const DiffFloat &grad_pol_y_re,
            const DiffFloat &grad_pol_y_im,
            const DiffFloat &grad_pol_z_re,
            const DiffFloat &grad_pol_z_im
        ) {
            size_t n_ray = static_cast<size_t>(n_rays);
            DiffFloat grad_prev_refl_p_x = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_refl_p_y = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_refl_p_z = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_refl_n_x = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_refl_n_y = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_refl_n_z = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_tx_x = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_tx_y = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_tx_z = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_weight_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_weight_im = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_pol_x_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_pol_x_im = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_pol_y_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_pol_y_im = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_pol_z_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_prev_pol_z_im = drjit::zeros<DiffFloat>(n_ray);
            drjit::eval(
                coord_0,
                coord_1,
                active,
                ray_origin_x,
                ray_origin_y,
                ray_origin_z,
                ray_dir_x,
                ray_dir_y,
                ray_dir_z,
                blocker_dist,
                prev_refl_p_x,
                prev_refl_p_y,
                prev_refl_p_z,
                prev_refl_n_x,
                prev_refl_n_y,
                prev_refl_n_z,
                prev_tx_x,
                prev_tx_y,
                prev_tx_z,
                prev_weight_re,
                prev_weight_im,
                prev_pol_x_re,
                prev_pol_x_im,
                prev_pol_y_re,
                prev_pol_y_im,
                prev_pol_z_re,
                prev_pol_z_im,
                prev_prim_idx,
                grad_field_re,
                grad_field_im,
                grad_pol_x_re,
                grad_pol_x_im,
                grad_pol_y_re,
                grad_pol_y_im,
                grad_pol_z_re,
                grad_pol_z_im,
                grad_prev_refl_p_x,
                grad_prev_refl_p_y,
                grad_prev_refl_p_z,
                grad_prev_refl_n_x,
                grad_prev_refl_n_y,
                grad_prev_refl_n_z,
                grad_prev_tx_x,
                grad_prev_tx_y,
                grad_prev_tx_z,
                grad_prev_weight_re,
                grad_prev_weight_im,
                grad_prev_pol_x_re,
                grad_prev_pol_x_im,
                grad_prev_pol_y_re,
                grad_prev_pol_y_im,
                grad_prev_pol_z_re,
                grad_prev_pol_z_im
            );
            if (has_mesh_data) {
                drjit::eval(
                    tri_v0_x, tri_v0_y, tri_v0_z,
                    tri_v1_x, tri_v1_y, tri_v1_z,
                    tri_v2_x, tri_v2_y, tri_v2_z,
                    tri_group_size, tri_group_members
                );
            }

            witwin::channel::native_ext::reflection_grid_backward(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                drjit_data_ptr(coord_0),
                drjit_data_ptr(coord_1),
                drjit_data_ptr(active),
                drjit_data_ptr(ray_origin_x),
                drjit_data_ptr(ray_origin_y),
                drjit_data_ptr(ray_origin_z),
                drjit_data_ptr(ray_dir_x),
                drjit_data_ptr(ray_dir_y),
                drjit_data_ptr(ray_dir_z),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(prev_refl_p_x),
                drjit_data_ptr(prev_refl_p_y),
                drjit_data_ptr(prev_refl_p_z),
                drjit_data_ptr(prev_refl_n_x),
                drjit_data_ptr(prev_refl_n_y),
                drjit_data_ptr(prev_refl_n_z),
                drjit_data_ptr(prev_tx_x),
                drjit_data_ptr(prev_tx_y),
                drjit_data_ptr(prev_tx_z),
                drjit_data_ptr(prev_weight_re),
                drjit_data_ptr(prev_weight_im),
                drjit_data_ptr(prev_pol_x_re),
                drjit_data_ptr(prev_pol_x_im),
                drjit_data_ptr(prev_pol_y_re),
                drjit_data_ptr(prev_pol_y_im),
                drjit_data_ptr(prev_pol_z_re),
                drjit_data_ptr(prev_pol_z_im),
                drjit_data_ptr(prev_prim_idx),
                validate_paths,
                has_mesh_data,
                has_mesh_data ? drjit_data_ptr(tri_v0_x) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v0_y) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v0_z) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v1_x) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v1_y) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v1_z) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v2_x) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v2_y) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_v2_z) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_group_size) : nullptr,
                has_mesh_data ? drjit_data_ptr(tri_group_members) : nullptr,
                max_group_size,
                wavelength,
                k,
                n_rays,
                drjit_data_ptr(grad_field_re),
                drjit_data_ptr(grad_field_im),
                drjit_data_ptr(grad_pol_x_re),
                drjit_data_ptr(grad_pol_x_im),
                drjit_data_ptr(grad_pol_y_re),
                drjit_data_ptr(grad_pol_y_im),
                drjit_data_ptr(grad_pol_z_re),
                drjit_data_ptr(grad_pol_z_im),
                drjit_data_ptr_mut(grad_prev_refl_p_x),
                drjit_data_ptr_mut(grad_prev_refl_p_y),
                drjit_data_ptr_mut(grad_prev_refl_p_z),
                drjit_data_ptr_mut(grad_prev_refl_n_x),
                drjit_data_ptr_mut(grad_prev_refl_n_y),
                drjit_data_ptr_mut(grad_prev_refl_n_z),
                drjit_data_ptr_mut(grad_prev_tx_x),
                drjit_data_ptr_mut(grad_prev_tx_y),
                drjit_data_ptr_mut(grad_prev_tx_z),
                drjit_data_ptr_mut(grad_prev_weight_re),
                drjit_data_ptr_mut(grad_prev_weight_im),
                drjit_data_ptr_mut(grad_prev_pol_x_re),
                drjit_data_ptr_mut(grad_prev_pol_x_im),
                drjit_data_ptr_mut(grad_prev_pol_y_re),
                drjit_data_ptr_mut(grad_prev_pol_y_im),
                drjit_data_ptr_mut(grad_prev_pol_z_re),
                drjit_data_ptr_mut(grad_prev_pol_z_im)
            );
            return nb::make_tuple(
                grad_prev_refl_p_x,
                grad_prev_refl_p_y,
                grad_prev_refl_p_z,
                grad_prev_refl_n_x,
                grad_prev_refl_n_y,
                grad_prev_refl_n_z,
                grad_prev_tx_x,
                grad_prev_tx_y,
                grad_prev_tx_z,
                grad_prev_weight_re,
                grad_prev_weight_im,
                grad_prev_pol_x_re,
                grad_prev_pol_x_im,
                grad_prev_pol_y_re,
                grad_prev_pol_y_im,
                grad_prev_pol_z_re,
                grad_prev_pol_z_im
            );
        },
        "Launch reflection-grid backward kernel with zero-copy Dr.Jit arrays."
    );
}
