#pragma once

namespace witwin::channel::native_ext {

void reflection_grid_forward(
    int plane_axis,
    float plane_position,
    float coord_0_min,
    float coord_0_max,
    float coord_1_min,
    float coord_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int max_steps,
    const float* coord_0,
    const float* coord_1,
    const int* active,
    const float* ray_origin_x,
    const float* ray_origin_y,
    const float* ray_origin_z,
    const float* ray_dir_x,
    const float* ray_dir_y,
    const float* ray_dir_z,
    const float* blocker_dist,
    const float* prev_refl_p_x,
    const float* prev_refl_p_y,
    const float* prev_refl_p_z,
    const float* prev_refl_n_x,
    const float* prev_refl_n_y,
    const float* prev_refl_n_z,
    const float* prev_tx_x,
    const float* prev_tx_y,
    const float* prev_tx_z,
    const float* prev_weight_re,
    const float* prev_weight_im,
    const float* prev_pol_x_re,
    const float* prev_pol_x_im,
    const float* prev_pol_y_re,
    const float* prev_pol_y_im,
    const float* prev_pol_z_re,
    const float* prev_pol_z_im,
    const int* prev_prim_idx,
    int validate_paths,
    int has_mesh_data,
    const float* tri_v0_x,
    const float* tri_v0_y,
    const float* tri_v0_z,
    const float* tri_v1_x,
    const float* tri_v1_y,
    const float* tri_v1_z,
    const float* tri_v2_x,
    const float* tri_v2_y,
    const float* tri_v2_z,
    const int* tri_group_size,
    const int* tri_group_members,
    int max_group_size,
    float wavelength,
    float k,
    int n_rays,
    float* out_field_re,
    float* out_field_im,
    float* out_count,
    float* out_pol_x_re,
    float* out_pol_x_im,
    float* out_pol_y_re,
    float* out_pol_y_im,
    float* out_pol_z_re,
    float* out_pol_z_im
);

void reflection_grid_jvp(
    int plane_axis,
    float plane_position,
    float coord_0_min,
    float coord_0_max,
    float coord_1_min,
    float coord_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int max_steps,
    const float* coord_0,
    const float* coord_1,
    const int* active,
    const float* ray_origin_x,
    const float* ray_origin_y,
    const float* ray_origin_z,
    const float* ray_dir_x,
    const float* ray_dir_y,
    const float* ray_dir_z,
    const float* blocker_dist,
    const float* prev_refl_p_x,
    const float* prev_refl_p_y,
    const float* prev_refl_p_z,
    const float* prev_refl_n_x,
    const float* prev_refl_n_y,
    const float* prev_refl_n_z,
    const float* prev_tx_x,
    const float* prev_tx_y,
    const float* prev_tx_z,
    const float* prev_weight_re,
    const float* prev_weight_im,
    const float* prev_pol_x_re,
    const float* prev_pol_x_im,
    const float* prev_pol_y_re,
    const float* prev_pol_y_im,
    const float* prev_pol_z_re,
    const float* prev_pol_z_im,
    const int* prev_prim_idx,
    int validate_paths,
    int has_mesh_data,
    const float* tri_v0_x,
    const float* tri_v0_y,
    const float* tri_v0_z,
    const float* tri_v1_x,
    const float* tri_v1_y,
    const float* tri_v1_z,
    const float* tri_v2_x,
    const float* tri_v2_y,
    const float* tri_v2_z,
    const int* tri_group_size,
    const int* tri_group_members,
    int max_group_size,
    const float* t_prev_refl_p_x,
    const float* t_prev_refl_p_y,
    const float* t_prev_refl_p_z,
    const float* t_prev_refl_n_x,
    const float* t_prev_refl_n_y,
    const float* t_prev_refl_n_z,
    const float* t_prev_tx_x,
    const float* t_prev_tx_y,
    const float* t_prev_tx_z,
    const float* t_prev_weight_re,
    const float* t_prev_weight_im,
    const float* t_prev_pol_x_re,
    const float* t_prev_pol_x_im,
    const float* t_prev_pol_y_re,
    const float* t_prev_pol_y_im,
    const float* t_prev_pol_z_re,
    const float* t_prev_pol_z_im,
    float wavelength,
    float k,
    int n_rays,
    float* out_field_re,
    float* out_field_im,
    float* out_pol_x_re,
    float* out_pol_x_im,
    float* out_pol_y_re,
    float* out_pol_y_im,
    float* out_pol_z_re,
    float* out_pol_z_im
);

void reflection_grid_backward(
    int plane_axis,
    float plane_position,
    float coord_0_min,
    float coord_0_max,
    float coord_1_min,
    float coord_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int max_steps,
    const float* coord_0,
    const float* coord_1,
    const int* active,
    const float* ray_origin_x,
    const float* ray_origin_y,
    const float* ray_origin_z,
    const float* ray_dir_x,
    const float* ray_dir_y,
    const float* ray_dir_z,
    const float* blocker_dist,
    const float* prev_refl_p_x,
    const float* prev_refl_p_y,
    const float* prev_refl_p_z,
    const float* prev_refl_n_x,
    const float* prev_refl_n_y,
    const float* prev_refl_n_z,
    const float* prev_tx_x,
    const float* prev_tx_y,
    const float* prev_tx_z,
    const float* prev_weight_re,
    const float* prev_weight_im,
    const float* prev_pol_x_re,
    const float* prev_pol_x_im,
    const float* prev_pol_y_re,
    const float* prev_pol_y_im,
    const float* prev_pol_z_re,
    const float* prev_pol_z_im,
    const int* prev_prim_idx,
    int validate_paths,
    int has_mesh_data,
    const float* tri_v0_x,
    const float* tri_v0_y,
    const float* tri_v0_z,
    const float* tri_v1_x,
    const float* tri_v1_y,
    const float* tri_v1_z,
    const float* tri_v2_x,
    const float* tri_v2_y,
    const float* tri_v2_z,
    const int* tri_group_size,
    const int* tri_group_members,
    int max_group_size,
    float wavelength,
    float k,
    int n_rays,
    const float* grad_field_re,
    const float* grad_field_im,
    const float* grad_pol_x_re,
    const float* grad_pol_x_im,
    const float* grad_pol_y_re,
    const float* grad_pol_y_im,
    const float* grad_pol_z_re,
    const float* grad_pol_z_im,
    float* grad_prev_refl_p_x,
    float* grad_prev_refl_p_y,
    float* grad_prev_refl_p_z,
    float* grad_prev_refl_n_x,
    float* grad_prev_refl_n_y,
    float* grad_prev_refl_n_z,
    float* grad_prev_tx_x,
    float* grad_prev_tx_y,
    float* grad_prev_tx_z,
    float* grad_prev_weight_re,
    float* grad_prev_weight_im,
    float* grad_prev_pol_x_re,
    float* grad_prev_pol_x_im,
    float* grad_prev_pol_y_re,
    float* grad_prev_pol_y_im,
    float* grad_prev_pol_z_re,
    float* grad_prev_pol_z_im
);

} // namespace witwin::channel::native_ext
