#pragma once

namespace witwin::channel::native_ext {

void radiomap_accumulate_vector_power_forward(
    const int* output_rx_idx,
    const float* pair_vec_x_re,
    const float* pair_vec_x_im,
    const float* pair_vec_y_re,
    const float* pair_vec_y_im,
    const float* pair_vec_z_re,
    const float* pair_vec_z_im,
    const float* arrival_x,
    const float* arrival_y,
    const float* arrival_z,
    float* coherent_re,
    float* coherent_im,
    float* power,
    float* vector_x_re,
    float* vector_x_im,
    float* vector_y_re,
    float* vector_y_im,
    float* vector_z_re,
    float* vector_z_im,
    float* valid_pair_count,
    int n_pairs,
    float rx_pol_x,
    float rx_pol_y,
    float rx_pol_z
);

void radiomap_vector_power_forward(
    const float* vec_x_re,
    const float* vec_x_im,
    const float* vec_y_re,
    const float* vec_y_im,
    const float* vec_z_re,
    const float* vec_z_im,
    float* power,
    int n_rx
);

void radiomap_vector_power_jvp(
    const float* vec_x_re,
    const float* vec_x_im,
    const float* vec_y_re,
    const float* vec_y_im,
    const float* vec_z_re,
    const float* vec_z_im,
    const float* t_vec_x_re,
    const float* t_vec_x_im,
    const float* t_vec_y_re,
    const float* t_vec_y_im,
    const float* t_vec_z_re,
    const float* t_vec_z_im,
    float* t_power,
    int n_rx
);

void radiomap_vector_power_backward(
    const float* vec_x_re,
    const float* vec_x_im,
    const float* vec_y_re,
    const float* vec_y_im,
    const float* vec_z_re,
    const float* vec_z_im,
    const float* grad_power,
    float* grad_vec_x_re,
    float* grad_vec_x_im,
    float* grad_vec_y_re,
    float* grad_vec_y_im,
    float* grad_vec_z_re,
    float* grad_vec_z_im,
    int n_rx
);

void radiomap_matched_isb_completion_forward(
    const float* continued_direct_re,
    const float* continued_direct_im,
    const float* tx_basis_x,
    const float* tx_basis_y,
    const float* tx_basis_z,
    const float* rx_basis_x,
    const float* rx_basis_y,
    const float* rx_basis_z,
    const float* hard_visibility,
    const int* interior_mask,
    const float* incident_weight,
    const float* incident_response_re,
    const float* incident_response_im,
    const float* raw_vec_x_re,
    const float* raw_vec_x_im,
    const float* raw_vec_y_re,
    const float* raw_vec_y_im,
    const float* raw_vec_z_re,
    const float* raw_vec_z_im,
    float* coherent_re,
    float* coherent_im,
    float* power,
    float* vector_x_re,
    float* vector_x_im,
    float* vector_y_re,
    float* vector_y_im,
    float* vector_z_re,
    float* vector_z_im,
    float* continued_direct_power,
    float* transition_magnitude,
    float* transition_phase,
    int n_rx
);

void radiomap_matched_isb_completion_jvp(
    const float* continued_direct_re,
    const float* continued_direct_im,
    const float* tx_basis_x,
    const float* tx_basis_y,
    const float* tx_basis_z,
    const float* rx_basis_x,
    const float* rx_basis_y,
    const float* rx_basis_z,
    const float* hard_visibility,
    const int* interior_mask,
    const float* incident_weight,
    const float* incident_response_re,
    const float* incident_response_im,
    const float* raw_vec_x_re,
    const float* raw_vec_x_im,
    const float* raw_vec_y_re,
    const float* raw_vec_y_im,
    const float* raw_vec_z_re,
    const float* raw_vec_z_im,
    const float* t_continued_direct_re,
    const float* t_continued_direct_im,
    const float* t_tx_basis_x,
    const float* t_tx_basis_y,
    const float* t_tx_basis_z,
    const float* t_rx_basis_x,
    const float* t_rx_basis_y,
    const float* t_rx_basis_z,
    const float* t_incident_weight,
    const float* t_incident_response_re,
    const float* t_incident_response_im,
    const float* t_raw_vec_x_re,
    const float* t_raw_vec_x_im,
    const float* t_raw_vec_y_re,
    const float* t_raw_vec_y_im,
    const float* t_raw_vec_z_re,
    const float* t_raw_vec_z_im,
    float* t_coherent_re,
    float* t_coherent_im,
    float* t_power,
    float* t_vector_x_re,
    float* t_vector_x_im,
    float* t_vector_y_re,
    float* t_vector_y_im,
    float* t_vector_z_re,
    float* t_vector_z_im,
    float* t_continued_direct_power,
    float* t_transition_magnitude,
    float* t_transition_phase,
    int n_rx
);

void radiomap_matched_isb_completion_backward(
    const float* continued_direct_re,
    const float* continued_direct_im,
    const float* tx_basis_x,
    const float* tx_basis_y,
    const float* tx_basis_z,
    const float* rx_basis_x,
    const float* rx_basis_y,
    const float* rx_basis_z,
    const float* hard_visibility,
    const int* interior_mask,
    const float* incident_weight,
    const float* incident_response_re,
    const float* incident_response_im,
    const float* raw_vec_x_re,
    const float* raw_vec_x_im,
    const float* raw_vec_y_re,
    const float* raw_vec_y_im,
    const float* raw_vec_z_re,
    const float* raw_vec_z_im,
    const float* grad_coherent_re,
    const float* grad_coherent_im,
    const float* grad_power,
    const float* grad_vector_x_re,
    const float* grad_vector_x_im,
    const float* grad_vector_y_re,
    const float* grad_vector_y_im,
    const float* grad_vector_z_re,
    const float* grad_vector_z_im,
    const float* grad_continued_direct_power,
    const float* grad_transition_magnitude,
    const float* grad_transition_phase,
    float* grad_continued_direct_re,
    float* grad_continued_direct_im,
    float* grad_tx_basis_x,
    float* grad_tx_basis_y,
    float* grad_tx_basis_z,
    float* grad_rx_basis_x,
    float* grad_rx_basis_y,
    float* grad_rx_basis_z,
    float* grad_incident_weight,
    float* grad_incident_response_re,
    float* grad_incident_response_im,
    float* grad_raw_vec_x_re,
    float* grad_raw_vec_x_im,
    float* grad_raw_vec_y_re,
    float* grad_raw_vec_y_im,
    float* grad_raw_vec_z_re,
    float* grad_raw_vec_z_im,
    int n_rx
);

void radiomap_shadow_boundary_incident_statistics_forward(
    const float* tx_x,
    const float* tx_y,
    const float* tx_z,
    const float* rx_x,
    const float* rx_y,
    const float* rx_z,
    const float* edge_pos_x,
    const float* edge_pos_y,
    const float* edge_pos_z,
    const float* edge_dir_x,
    const float* edge_dir_y,
    const float* edge_dir_z,
    const float* n0_x,
    const float* n0_y,
    const float* n0_z,
    const float* nn_x,
    const float* nn_y,
    const float* nn_z,
    const float* wedge_n,
    const float* edge_line_min,
    const float* edge_line_max,
    const int* source_visible,
    float* sum_incident_weight,
    float* max_incident_weight,
    float* weighted_incident_response_real,
    float* weighted_incident_response_imag,
    int* argmax_edge_idx,
    float* second_max_incident_weight,
    int* support_edge_count,
    int n_rx,
    int n_edges,
    float k
);

void radiomap_shadow_boundary_incident_statistics_jvp(
    const float* tx_x,
    const float* tx_y,
    const float* tx_z,
    const float* rx_x,
    const float* rx_y,
    const float* rx_z,
    const float* edge_pos_x,
    const float* edge_pos_y,
    const float* edge_pos_z,
    const float* edge_dir_x,
    const float* edge_dir_y,
    const float* edge_dir_z,
    const float* n0_x,
    const float* n0_y,
    const float* n0_z,
    const float* nn_x,
    const float* nn_y,
    const float* nn_z,
    const float* wedge_n,
    const float* edge_line_min,
    const float* edge_line_max,
    const int* source_visible,
    const int* argmax_edge_idx,
    const float* t_tx_x,
    const float* t_tx_y,
    const float* t_tx_z,
    const float* t_rx_x,
    const float* t_rx_y,
    const float* t_rx_z,
    const float* t_edge_pos_x,
    const float* t_edge_pos_y,
    const float* t_edge_pos_z,
    float* t_sum_incident_weight,
    float* t_max_incident_weight,
    float* t_weighted_incident_response_real,
    float* t_weighted_incident_response_imag,
    int n_rx,
    int n_edges,
    float k
);

void radiomap_shadow_boundary_incident_statistics_backward(
    const float* tx_x,
    const float* tx_y,
    const float* tx_z,
    const float* rx_x,
    const float* rx_y,
    const float* rx_z,
    const float* edge_pos_x,
    const float* edge_pos_y,
    const float* edge_pos_z,
    const float* edge_dir_x,
    const float* edge_dir_y,
    const float* edge_dir_z,
    const float* n0_x,
    const float* n0_y,
    const float* n0_z,
    const float* nn_x,
    const float* nn_y,
    const float* nn_z,
    const float* wedge_n,
    const float* edge_line_min,
    const float* edge_line_max,
    const int* source_visible,
    const int* argmax_edge_idx,
    const float* grad_sum_incident_weight,
    const float* grad_max_incident_weight,
    const float* grad_weighted_incident_response_real,
    const float* grad_weighted_incident_response_imag,
    float* grad_tx_x,
    float* grad_tx_y,
    float* grad_tx_z,
    float* grad_rx_x,
    float* grad_rx_y,
    float* grad_rx_z,
    float* grad_edge_pos_x,
    float* grad_edge_pos_y,
    float* grad_edge_pos_z,
    int n_rx,
    int n_edges,
    float k
);

} // namespace witwin::channel::native_ext
