"""Compatibility facade for the canonical reference oracle."""

from witwin.channel.physics.reference.oracle import (
    C0,
    EPS0,
    ETA0,
    MU0,
    Medium,
    RTCoefficients,
    Sequence as Sequence,
    _admittances as _admittances,
    _interface_rt as _interface_rt,
    _power_coefficients as _power_coefficients,
    _stack_rt_one_pol as _stack_rt_one_pol,
    coherent_attenuation,
    complex_sqrt_passive,
    dataclass as dataclass,
    fresnel_interface,
    hemisphere_integral,
    kirchhoff_diffuse_lobe_quadrature,
    kirchhoff_diffuse_lobe_series,
    layer_stack_rt,
    medium_params,
    np as np,
    phase_screen_patch_integral,
    refraction_direction,
    vacuum_medium,
)
from witwin.channel.physics.reference.oracle import Callable as Callable

__all__ = [
    "C0",
    "EPS0",
    "ETA0",
    "MU0",
    "Medium",
    "RTCoefficients",
    "coherent_attenuation",
    "complex_sqrt_passive",
    "fresnel_interface",
    "hemisphere_integral",
    "kirchhoff_diffuse_lobe_quadrature",
    "kirchhoff_diffuse_lobe_series",
    "layer_stack_rt",
    "medium_params",
    "phase_screen_patch_integral",
    "refraction_direction",
    "vacuum_medium",
]
