from __future__ import annotations

from .autograd import (
    _RaydFaceNormalsAdFunction,
    _RaydIntersectAdFunction,
    _RaydReflectionEpcPathsAdFunction,
    _RaydTraceReflectionsAdFunction,
    _epc_paths_frozen_winner_checks,
    rayd_face_normals_ad,
    rayd_intersect_ad,
    rayd_intersect_backward,
    rayd_intersect_jvp,
    rayd_reflection_epc_paths_ad,
    rayd_reflection_epc_paths_backward,
    rayd_reflection_epc_paths_jvp,
    rayd_scene_face_normals_backward,
    rayd_scene_face_normals_jvp,
    rayd_trace_reflections_ad,
    rayd_trace_reflections_backward,
    rayd_trace_reflections_forward_tape,
    rayd_trace_reflections_jvp,
)
from .bridge import (
    bdpt_diffraction_accumulation_forward,
    coupled_rd_geometry_forward,
    rayd_diffraction_paths_order1_forward,
    rayd_intersect_forward,
    rayd_reflection_epc_paths_forward,
    rayd_trace_reflections_forward,
    rayd_visibility_forward,
)
from .primitives import (
    core_diffraction_edge_count,
    deterministic_face_groups,
    deterministic_normalize_vec3,
    deterministic_reflect_points,
    deterministic_surface_face_groups,
    mc_diffraction_edge_geometry,
    mc_surface_group_edge_candidates,
)


__all__ = [
    "_RaydFaceNormalsAdFunction",
    "_RaydIntersectAdFunction",
    "_RaydReflectionEpcPathsAdFunction",
    "_RaydTraceReflectionsAdFunction",
    "_epc_paths_frozen_winner_checks",
    "bdpt_diffraction_accumulation_forward",
    "core_diffraction_edge_count",
    "deterministic_face_groups",
    "deterministic_normalize_vec3",
    "deterministic_reflect_points",
    "deterministic_surface_face_groups",
    "mc_diffraction_edge_geometry",
    "mc_surface_group_edge_candidates",
    "coupled_rd_geometry_forward",
    "rayd_diffraction_paths_order1_forward",
    "rayd_face_normals_ad",
    "rayd_intersect_ad",
    "rayd_intersect_backward",
    "rayd_intersect_jvp",
    "rayd_intersect_forward",
    "rayd_reflection_epc_paths_ad",
    "rayd_reflection_epc_paths_backward",
    "rayd_reflection_epc_paths_forward",
    "rayd_reflection_epc_paths_jvp",
    "rayd_scene_face_normals_backward",
    "rayd_scene_face_normals_jvp",
    "rayd_trace_reflections_ad",
    "rayd_trace_reflections_backward",
    "rayd_trace_reflections_forward",
    "rayd_trace_reflections_forward_tape",
    "rayd_trace_reflections_jvp",
    "rayd_visibility_forward",
]
