#pragma once

namespace witwin::channel::native_ext {

void monte_carlo_diffraction_sample_slots(
    const unsigned int *sample_index,
    const float *cdf,
    unsigned int *out_slots,
    int n_samples,
    int n_states,
    float total_length_scalar,
    int seed
);

void monte_carlo_diffraction_best_edge_indices(
    float tx_x,
    float tx_y,
    float tx_z,
    const float *ray_dir_x,
    const float *ray_dir_y,
    const float *ray_dir_z,
    const float *hit_p_x,
    const float *hit_p_y,
    const float *hit_p_z,
    const float *hit_n_x,
    const float *hit_n_y,
    const float *hit_n_z,
    const float *hit_geo_n_x,
    const float *hit_geo_n_y,
    const float *hit_geo_n_z,
    const int *hit_mask,
    const unsigned int *triangle_edge_count,
    const int *triangle_edge_indices,
    int max_triangle_edge_slots,
    const float *edge_pos_x,
    const float *edge_pos_y,
    const float *edge_pos_z,
    const float *edge_dir_x,
    const float *edge_dir_y,
    const float *edge_dir_z,
    const float *edge_n0_x,
    const float *edge_n0_y,
    const float *edge_n0_z,
    const float *edge_nn_x,
    const float *edge_nn_y,
    const float *edge_nn_z,
    const float *edge_line_min,
    const float *edge_line_max,
    const int *edge_adjacent_face1,
    int n_edges,
    int n_rays,
    int *out_best_edge_idx
);

void monte_carlo_diffraction_discover_edges(
    float tx_x,
    float tx_y,
    float tx_z,
    const float *ray_dir_x,
    const float *ray_dir_y,
    const float *ray_dir_z,
    const int *prim_index,
    const float *hit_p_x,
    const float *hit_p_y,
    const float *hit_p_z,
    const float *hit_n_x,
    const float *hit_n_y,
    const float *hit_n_z,
    const float *hit_geo_n_x,
    const float *hit_geo_n_y,
    const float *hit_geo_n_z,
    int n_hits,
    const unsigned int *triangle_edge_count,
    const int *triangle_edge_indices,
    int max_triangle_edge_slots,
    int n_triangles,
    const float *edge_pos_x,
    const float *edge_pos_y,
    const float *edge_pos_z,
    const float *edge_dir_x,
    const float *edge_dir_y,
    const float *edge_dir_z,
    const float *edge_n0_x,
    const float *edge_n0_y,
    const float *edge_n0_z,
    const float *edge_nn_x,
    const float *edge_nn_y,
    const float *edge_nn_z,
    const float *edge_line_min,
    const float *edge_line_max,
    const int *edge_adjacent_face1,
    int n_edges,
    unsigned int *out_seen_edge_mask
);

void monte_carlo_diffraction_build_state_arrays(
    const unsigned int *edge_idx,
    int n_states,
    float tx_x,
    float tx_y,
    float tx_z,
    const float *edge_pos_x,
    const float *edge_pos_y,
    const float *edge_pos_z,
    const float *edge_dir_x,
    const float *edge_dir_y,
    const float *edge_dir_z,
    const float *edge_n0_x,
    const float *edge_n0_y,
    const float *edge_n0_z,
    const float *edge_nn_x,
    const float *edge_nn_y,
    const float *edge_nn_z,
    const float *edge_wedge_n,
    const float *edge_line_min,
    const float *edge_line_max,
    const int *edge_adjacent_face0,
    const int *edge_adjacent_face1,
    int *out_edge_index,
    float *out_edge_pos_x,
    float *out_edge_pos_y,
    float *out_edge_pos_z,
    float *out_edge_dir_x,
    float *out_edge_dir_y,
    float *out_edge_dir_z,
    float *out_n0_x,
    float *out_n0_y,
    float *out_n0_z,
    float *out_nn_x,
    float *out_nn_y,
    float *out_nn_z,
    float *out_wedge_n,
    float *out_line_min,
    float *out_line_max,
    float *out_source_pos_x,
    float *out_source_pos_y,
    float *out_source_pos_z,
    int *out_adjacent_face0,
    int *out_adjacent_face1
);

} // namespace witwin::channel::native_ext
