from __future__ import annotations

from witwin.channel_native.core.rayd_native_handles import (  # noqa: F401
    _raydn_module_handle,
    _raydn_scene_handle_id,
)
from witwin.channel_native.propagation.topology.kernels.blocks import (  # noqa: F401
    _DETERMINISTIC_TOPOLOGY_EXTRA_SCHEMA,
    _PATH_BLOCK_SCHEMA,
    _validate_deterministic_topology_block,
    _validate_path_block,
    _validate_path_reflection_candidates,
    _validate_topology_extra_fields,
    deterministic_concat_topology_blocks,
    deterministic_gather_topology_block,
    path_diffraction_block,
    path_filter_block,
    path_filter_los,
    path_finalize_blocks,
    path_los_export,
    path_los_visibility_inputs,
    path_merge_blocks,
)
from witwin.channel_native.propagation.topology.kernels.candidates import (  # noqa: F401
    path_diffraction_paths_order1,
    path_reflection_candidates,
)
from witwin.channel_native.propagation.topology.kernels.compaction import (  # noqa: F401
    deterministic_diffraction_order1_compact,
    deterministic_reflection_order1_compact,
    deterministic_reflection_sequence_compact,
    deterministic_sort_order,
)
from witwin.channel_native.propagation.topology.kernels.construction import (  # noqa: F401
    deterministic_face_anchor_points,
    deterministic_face_sequence_chunk,
    deterministic_los_topology_block,
    deterministic_mapped_face_sequence_chunk,
    deterministic_pad_topology_sequences,
    deterministic_reflection_epc_input_batch,
    deterministic_repeat_range,
    deterministic_topology_base_fields,
    deterministic_topology_default_fields,
)
from witwin.channel_native.propagation.topology.kernels.primitives import (  # noqa: F401
    core_pack_int2,
    deterministic_component_counts,
    deterministic_diffraction_state_pack,
    deterministic_diffraction_state_pack_selected,
    deterministic_selected_edge_count,
    mc_selected_edge_indices,
    path_concat_vec3,
)
from witwin.channel_native.scattering.kernels.functional import (  # noqa: F401
    scattering_event_probabilities,
    scattering_table_eval,
    scattering_table_pdf,
    scattering_table_sample,
)
from witwin.channel_native.materials.kernels.functional import (  # noqa: F401
    _EM_LAYER_STACK_FIELDS,
    bdpt_face_material_tensors,
    bdpt_face_material_tensors_from_host,
    em_layer_stack_backward,
    em_layer_stack_eval,
    em_layer_stack_jvp,
    mc_face_material_tensors,
)
from witwin.channel_native.materials.kernels.autograd import (  # noqa: F401
    _EmLayerStackAdFunction,
    em_layer_stack_ad,
)
from witwin.channel_native.materials.kernels.contracts import _validate_layer_csr  # noqa: F401
from witwin.channel_native.propagation.fields.kernels.autograd import (  # noqa: F401
    _CoupledRdPrepareAdFunction,
    _FieldCoupledRdAdFunction,
    _FieldDiffractionWedgeAdFunction,
    _FieldFreeSpaceAdFunction,
    _FieldProjectComplex3AdFunction,
    _FieldReflectionSequenceAdFunction,
    _FieldTransmissionSequenceAdFunction,
    coupled_rd_prepare_ad,
    field_coupled_rd_ad,
    field_diffraction_wedge_ad,
    field_free_space_ad,
    field_project_complex3_ad,
    field_reflection_sequence_ad,
    field_transmission_sequence_ad,
)
from witwin.channel_native.propagation.fields.kernels.functional import (  # noqa: F401
    _COUPLED_OUTPUT_FIELDS,
    _FIELD_AD_OUTPUT_FIELDS,
    _FIELD_AD_TANGENT_FIELDS,
    _WEDGE_OUTPUT_FIELDS,
    field_coupled_rd,
    field_diffraction_wedge,
    field_free_space,
    field_free_space_backward,
    field_free_space_jvp,
    field_project_complex3,
    field_reflection_sequence,
    field_reflection_sequence_backward,
    field_reflection_sequence_jvp,
    field_transmission_sequence,
    field_transmission_sequence_backward,
    field_transmission_sequence_jvp,
)
from witwin.channel_native.propagation.geometry.kernels.bridge import (  # noqa: F401
    bdpt_diffraction_accumulation_forward,
    bdpt_diffraction_discover_edges,
    bdpt_diffraction_discover_edges_counted,
    bdpt_intersect_forward,
    bdpt_reflection_accumulation_forward,
    bdpt_visibility_forward,
    raydn_coupled_rd_geometry_forward,
    raydn_diffraction_accumulation_forward,
    raydn_diffraction_discover_edges,
    raydn_diffraction_discover_edges_counted,
    raydn_diffraction_paths_order1_forward,
    raydn_reflection_accumulation_forward,
    raydn_reflection_epc_paths_forward,
    raydn_trace_reflections_forward,
    raydn_visibility_forward,
)
from witwin.channel_native.propagation.geometry.kernels.autograd import (  # noqa: F401
    _RaydnFaceNormalsAdFunction,
    _RaydnIntersectAdFunction,
    _RaydnReflectionEpcPathsAdFunction,
    _RaydnTraceReflectionsAdFunction,
    _epc_paths_frozen_winner_checks,
    raydn_face_normals_ad,
    raydn_intersect_ad,
    raydn_intersect_backward,
    raydn_intersect_jvp,
    raydn_reflection_epc_paths_ad,
    raydn_reflection_epc_paths_backward,
    raydn_reflection_epc_paths_jvp,
    raydn_scene_face_normals_backward,
    raydn_scene_face_normals_jvp,
    raydn_trace_reflections_ad,
    raydn_trace_reflections_backward,
    raydn_trace_reflections_forward_tape,
    raydn_trace_reflections_jvp,
)
from witwin.channel_native.propagation.geometry.kernels.primitives import (  # noqa: F401
    bdpt_diffraction_edge_geometry,
    bdpt_surface_group_edge_candidates,
    core_diffraction_edge_count,
    deterministic_face_groups,
    deterministic_normalize_vec3,
    deterministic_reflect_points,
    deterministic_surface_face_groups,
    mc_diffraction_edge_geometry,
    mc_surface_group_edge_candidates,
)
from witwin.channel_native.runtime.symbols import (  # noqa: F401
    _required_native_op,
    native_extension,
)
from witwin.channel_native.runtime.tensor_contracts import validate_cuda_tensor  # noqa: F401
from witwin.channel_native.runtime.autograd_contracts import (  # noqa: F401
    _ad_active_ctx,
    _ad_check_active,
    _ad_check_optional_grad,
    _ad_check_rows,
    _ad_check_tangent_vec3,
    _ad_checked_tangent,
    _ad_frequency_grad,
    _ad_frequency_tangent,
    _ad_frequency_value,
    _ad_geometry_live,
    _ad_geometry_tangent,
    _ad_native_tangent_or_none,
    _ad_native_tensor,
    _ad_raise_composed_transforms,
    _ad_reject_fixed_inputs,
    _ad_reject_fixed_tangents,
    _ad_still_wrapped,
)
from witwin.channel_native.scene.kernels.rayd_scene import raydn_scene_create, raydn_scene_edge_records  # noqa: F401

from .metadata import make_metadata, noop_metadata, validate_metadata  # noqa: F401


# Keep eager-domain imports late to preserve the facade's verified import order.
from witwin.channel_native.deterministic.kernels.accumulation import (  # noqa: E402,F401
    _DETERMINISTIC_ACCUM_FIELDS,
    _DeterministicAccumulateFlatAdFunction,
    deterministic_accumulate_flat,
    deterministic_accumulate_flat_ad,
    deterministic_accumulate_flat_backward,
    deterministic_accumulate_flat_jvp,
)
from witwin.channel_native.deterministic.kernels.fields import (  # noqa: E402,F401
    deterministic_delay_to_path_length,
    deterministic_diffraction_vector_field,
    deterministic_field_from_power_phase,
    deterministic_los_field,
    deterministic_pack_complex,
    deterministic_phase_from_field,
    deterministic_phase_from_length,
    deterministic_reflection_field,
    deterministic_reflection_sequence_field,
    deterministic_zero_field_phase,
)
from witwin.channel_native.montecarlo.bdpt.kernels.maps import (  # noqa: E402,F401
    bdpt_apply_los_visibility,
    bdpt_component_map_buffer,
    bdpt_finalize_component_maps,
    bdpt_finalize_point_components,
    bdpt_host_vec3_tensor,
    bdpt_los_component_maps,
    bdpt_los_component_maps_from_matrix,
    bdpt_los_export,
    bdpt_los_visibility_inputs,
    bdpt_point_component_power,
    bdpt_receiver_grid_points,
    bdpt_store_component_map,
    bdpt_store_point_component_column,
    bdpt_store_scaled_component_map,
    bdpt_transmitter_tensors,
    bdpt_zero_matrix,
)
from witwin.channel_native.montecarlo.bdpt.kernels.sampling import (  # noqa: E402,F401
    bdpt_diffraction_state_pack,
    bdpt_diffraction_state_wi,
    bdpt_pack_vec3,
    bdpt_reflection_launch_inputs,
    bdpt_sample_directions,
    bdpt_selected_edge_indices,
)
from witwin.channel_native.montecarlo.basic.kernels.sampling import (  # noqa: E402,F401
    mc_diffraction_state_pack,
    mc_diffraction_state_wi,
    mc_pack_vec3,
    mc_receiver_grid_points,
    mc_reflection_launch_inputs,
    mc_sample_directions,
    mc_transmitter_tensors,
)
from witwin.channel_native.montecarlo.basic.kernels.maps import (  # noqa: E402,F401
    _LIGHT_SPEED_M_PER_S_AD,
    _MC_FINALIZE_FIELDS,
    _McFinalizeComponentMapsAdFunction,
    _McDiffractionMapAdFunction,
    _McLosGridMapsAdFunction,
    _McLosPathGainAdFunction,
    _McReflectionMapAdFunction,
    mc_apply_los_visibility,
    mc_component_map_buffer,
    mc_finalize_component_maps,
    mc_finalize_component_maps_ad,
    mc_los_component_maps,
    mc_los_component_maps_adjoint,
    mc_los_component_maps_from_matrix,
    mc_los_grid_maps_ad,
    mc_los_path_gain_ad,
    mc_los_path_gain_backward,
    mc_los_path_gain_jvp,
    mc_los_visibility_inputs,
    mc_point_component_power,
    mc_reflection_ad_max_depth,
    mc_sionna_diffraction_tape_accumulate,
    mc_sionna_diffraction_tape_accumulate_ad,
    mc_sionna_diffraction_tape_accumulate_backward,
    mc_sionna_diffraction_tape_accumulate_jvp,
    mc_sionna_reflection_accumulate,
    mc_sionna_reflection_accumulate_ad,
    mc_sionna_reflection_accumulate_backward,
    mc_sionna_reflection_accumulate_jvp,
    mc_store_component_map,
    mc_store_scaled_component_map,
    mc_zero_matrix,
)
from witwin.channel_native.montecarlo.bdpt.kernels.paths import (  # noqa: E402,F401
    _BDPT_CONNECTION_SCHEMA,
    _BDPT_SUBPATH_SCHEMA,
    _bdpt_mis_mode_id,
    _validate_bdpt_connection_samples,
    _validate_bdpt_subpath_state,
    bdpt_accumulate_connection_samples,
    bdpt_compact_connection_samples,
    bdpt_concat_connection_samples,
    bdpt_connection_variance,
    bdpt_count_valid_connection_samples,
    bdpt_diffraction_connection_samples_from_tape,
    bdpt_diffraction_point_connection_samples,
    bdpt_empty_subpath_state,
    bdpt_endpoint_connection_samples,
    bdpt_endpoint_connection_visibility_inputs,
    bdpt_endpoint_subpath_state,
    bdpt_filter_connection_samples,
    bdpt_launch_state,
    bdpt_mis_weights,
    bdpt_reflected_light_subpath_state,
    bdpt_subpath_intersection_inputs,
    bdpt_transmitted_light_subpath_state,
)
