#pragma once

#include <cstdint>

namespace witwin::channel::native_ext {

void suffix_segment_tile_plan_count(
    float bound_0_min,
    float bound_0_max,
    float bound_1_min,
    float bound_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int tile_shape_0,
    int tile_shape_1,
    int max_steps,
    const float* origin_0,
    const float* origin_1,
    const float* dir_0,
    const float* dir_1,
    const float* blocker_dist,
    const int* active,
    int n_segments,
    std::uint32_t* out_segment_tile_counts
);

std::uint32_t suffix_segment_tile_plan_scan(
    const std::uint32_t* segment_tile_counts,
    int n_segments,
    std::uint32_t* out_segment_offsets
);

void suffix_segment_tile_plan_write(
    float bound_0_min,
    float bound_0_max,
    float bound_1_min,
    float bound_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int tile_shape_0,
    int tile_shape_1,
    int max_steps,
    const float* origin_0,
    const float* origin_1,
    const float* dir_0,
    const float* dir_1,
    const float* blocker_dist,
    const int* active,
    int n_segments,
    const std::uint32_t* segment_offsets,
    std::uint32_t* out_task_segment_idx,
    std::uint32_t* out_task_tile_idx,
    float* out_entry_coord_0,
    float* out_entry_coord_1,
    float* out_entry_t,
    float* out_entry_t_max_0,
    float* out_entry_t_max_1
);

void suffix_grid_forward(
    int plane_axis,
    float plane_position,
    float coord_0_min,
    float coord_0_max,
    float coord_1_min,
    float coord_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int max_steps,
    const float* coord_0,
    const float* coord_1,
    const int* active,
    const int* task_segment_idx,
    const float* seg_origin_x,
    const float* seg_origin_y,
    const float* seg_origin_z,
    const float* seg_dir_x,
    const float* seg_dir_y,
    const float* seg_dir_z,
    const float* blocker_dist,
    const float* seg_field_re,
    const float* seg_field_im,
    const float* seg_vec_x_re,
    const float* seg_vec_x_im,
    const float* seg_vec_y_re,
    const float* seg_vec_y_im,
    const float* seg_vec_z_re,
    const float* seg_vec_z_im,
    float wavelength,
    float k,
    int n_rays,
    float* out_field_re,
    float* out_field_im,
    float* out_vec_x_re,
    float* out_vec_x_im,
    float* out_vec_y_re,
    float* out_vec_y_im,
    float* out_vec_z_re,
    float* out_vec_z_im
);

void suffix_grid_forward_resume(
    int plane_axis,
    float plane_position,
    float coord_0_min,
    float coord_0_max,
    float coord_1_min,
    float coord_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int max_steps,
    const float* coord_0,
    const float* coord_1,
    const int* active,
    const float* seg_origin_x,
    const float* seg_origin_y,
    const float* seg_origin_z,
    const float* seg_dir_x,
    const float* seg_dir_y,
    const float* seg_dir_z,
    const float* blocker_dist,
    const float* seg_field_re,
    const float* seg_field_im,
    const float* seg_vec_x_re,
    const float* seg_vec_x_im,
    const float* seg_vec_y_re,
    const float* seg_vec_y_im,
    const float* seg_vec_z_re,
    const float* seg_vec_z_im,
    const float* trace_coord_0,
    const float* trace_coord_1,
    const float* trace_t,
    const float* trace_t_max_0,
    const float* trace_t_max_1,
    float wavelength,
    float k,
    int n_rays,
    float* out_field_re,
    float* out_field_im,
    float* out_vec_x_re,
    float* out_vec_x_im,
    float* out_vec_y_re,
    float* out_vec_y_im,
    float* out_vec_z_re,
    float* out_vec_z_im
);

void suffix_grid_jvp(
    int plane_axis,
    float plane_position,
    float coord_0_min,
    float coord_0_max,
    float coord_1_min,
    float coord_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int max_steps,
    const float* coord_0,
    const float* coord_1,
    const int* active,
    const int* task_segment_idx,
    const float* seg_origin_x,
    const float* seg_origin_y,
    const float* seg_origin_z,
    const float* seg_dir_x,
    const float* seg_dir_y,
    const float* seg_dir_z,
    const float* blocker_dist,
    const float* seg_field_re,
    const float* seg_field_im,
    const float* seg_vec_x_re,
    const float* seg_vec_x_im,
    const float* seg_vec_y_re,
    const float* seg_vec_y_im,
    const float* seg_vec_z_re,
    const float* seg_vec_z_im,
    const float* t_seg_origin_x,
    const float* t_seg_origin_y,
    const float* t_seg_origin_z,
    const float* t_seg_field_re,
    const float* t_seg_field_im,
    const float* t_seg_vec_x_re,
    const float* t_seg_vec_x_im,
    const float* t_seg_vec_y_re,
    const float* t_seg_vec_y_im,
    const float* t_seg_vec_z_re,
    const float* t_seg_vec_z_im,
    float wavelength,
    float k,
    int n_rays,
    float* out_field_re,
    float* out_field_im,
    float* out_vec_x_re,
    float* out_vec_x_im,
    float* out_vec_y_re,
    float* out_vec_y_im,
    float* out_vec_z_re,
    float* out_vec_z_im
);

void suffix_grid_jvp_resume(
    int plane_axis,
    float plane_position,
    float coord_0_min,
    float coord_0_max,
    float coord_1_min,
    float coord_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int max_steps,
    const float* coord_0,
    const float* coord_1,
    const int* active,
    const float* seg_origin_x,
    const float* seg_origin_y,
    const float* seg_origin_z,
    const float* seg_dir_x,
    const float* seg_dir_y,
    const float* seg_dir_z,
    const float* blocker_dist,
    const float* seg_field_re,
    const float* seg_field_im,
    const float* seg_vec_x_re,
    const float* seg_vec_x_im,
    const float* seg_vec_y_re,
    const float* seg_vec_y_im,
    const float* seg_vec_z_re,
    const float* seg_vec_z_im,
    const float* trace_coord_0,
    const float* trace_coord_1,
    const float* trace_t,
    const float* trace_t_max_0,
    const float* trace_t_max_1,
    const float* t_seg_origin_x,
    const float* t_seg_origin_y,
    const float* t_seg_origin_z,
    const float* t_seg_field_re,
    const float* t_seg_field_im,
    const float* t_seg_vec_x_re,
    const float* t_seg_vec_x_im,
    const float* t_seg_vec_y_re,
    const float* t_seg_vec_y_im,
    const float* t_seg_vec_z_re,
    const float* t_seg_vec_z_im,
    float wavelength,
    float k,
    int n_rays,
    float* out_field_re,
    float* out_field_im,
    float* out_vec_x_re,
    float* out_vec_x_im,
    float* out_vec_y_re,
    float* out_vec_y_im,
    float* out_vec_z_re,
    float* out_vec_z_im
);

void suffix_grid_backward(
    int plane_axis,
    float plane_position,
    float coord_0_min,
    float coord_0_max,
    float coord_1_min,
    float coord_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int max_steps,
    const float* coord_0,
    const float* coord_1,
    const int* active,
    const int* task_segment_idx,
    const float* seg_origin_x,
    const float* seg_origin_y,
    const float* seg_origin_z,
    const float* seg_dir_x,
    const float* seg_dir_y,
    const float* seg_dir_z,
    const float* blocker_dist,
    const float* seg_field_re,
    const float* seg_field_im,
    const float* seg_vec_x_re,
    const float* seg_vec_x_im,
    const float* seg_vec_y_re,
    const float* seg_vec_y_im,
    const float* seg_vec_z_re,
    const float* seg_vec_z_im,
    float wavelength,
    float k,
    int n_rays,
    const float* grad_field_re,
    const float* grad_field_im,
    const float* grad_vec_x_re,
    const float* grad_vec_x_im,
    const float* grad_vec_y_re,
    const float* grad_vec_y_im,
    const float* grad_vec_z_re,
    const float* grad_vec_z_im,
    float* grad_seg_origin_x,
    float* grad_seg_origin_y,
    float* grad_seg_origin_z,
    float* grad_seg_field_re,
    float* grad_seg_field_im,
    float* grad_seg_vec_x_re,
    float* grad_seg_vec_x_im,
    float* grad_seg_vec_y_re,
    float* grad_seg_vec_y_im,
    float* grad_seg_vec_z_re,
    float* grad_seg_vec_z_im
);

void suffix_grid_backward_resume(
    int plane_axis,
    float plane_position,
    float coord_0_min,
    float coord_0_max,
    float coord_1_min,
    float coord_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int max_steps,
    const float* coord_0,
    const float* coord_1,
    const int* active,
    const float* seg_origin_x,
    const float* seg_origin_y,
    const float* seg_origin_z,
    const float* seg_dir_x,
    const float* seg_dir_y,
    const float* seg_dir_z,
    const float* blocker_dist,
    const float* seg_field_re,
    const float* seg_field_im,
    const float* seg_vec_x_re,
    const float* seg_vec_x_im,
    const float* seg_vec_y_re,
    const float* seg_vec_y_im,
    const float* seg_vec_z_re,
    const float* seg_vec_z_im,
    const float* trace_coord_0,
    const float* trace_coord_1,
    const float* trace_t,
    const float* trace_t_max_0,
    const float* trace_t_max_1,
    float wavelength,
    float k,
    int n_rays,
    const float* grad_field_re,
    const float* grad_field_im,
    const float* grad_vec_x_re,
    const float* grad_vec_x_im,
    const float* grad_vec_y_re,
    const float* grad_vec_y_im,
    const float* grad_vec_z_re,
    const float* grad_vec_z_im,
    float* grad_seg_origin_x,
    float* grad_seg_origin_y,
    float* grad_seg_origin_z,
    float* grad_seg_field_re,
    float* grad_seg_field_im,
    float* grad_seg_vec_x_re,
    float* grad_seg_vec_x_im,
    float* grad_seg_vec_y_re,
    float* grad_seg_vec_y_im,
    float* grad_seg_vec_z_re,
    float* grad_seg_vec_z_im
);

void suffix_grid_forward_resume_batched(
    int plane_axis,
    float plane_position,
    float coord_0_min,
    float coord_0_max,
    float coord_1_min,
    float coord_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int max_steps,
    const float* coord_0,
    const float* coord_1,
    const int* active,
    const int* task_segment_idx,
    const float* seg_origin_x,
    const float* seg_origin_y,
    const float* seg_origin_z,
    const float* seg_dir_x,
    const float* seg_dir_y,
    const float* seg_dir_z,
    const float* blocker_dist,
    const float* seg_field_re,
    const float* seg_field_im,
    const float* seg_vec_x_re,
    const float* seg_vec_x_im,
    const float* seg_vec_y_re,
    const float* seg_vec_y_im,
    const float* seg_vec_z_re,
    const float* seg_vec_z_im,
    const float* trace_coord_0,
    const float* trace_coord_1,
    const float* trace_t,
    const float* trace_t_max_0,
    const float* trace_t_max_1,
    const int* tile_i0,
    const int* tile_i1,
    const int* tile_extent_0,
    const int* tile_extent_1,
    float wavelength,
    float k,
    int n_rays,
    float* out_field_re,
    float* out_field_im,
    float* out_vec_x_re,
    float* out_vec_x_im,
    float* out_vec_y_re,
    float* out_vec_y_im,
    float* out_vec_z_re,
    float* out_vec_z_im
);

void suffix_grid_jvp_resume_batched(
    int plane_axis,
    float plane_position,
    float coord_0_min,
    float coord_0_max,
    float coord_1_min,
    float coord_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int max_steps,
    const float* coord_0,
    const float* coord_1,
    const int* active,
    const int* task_segment_idx,
    const float* seg_origin_x,
    const float* seg_origin_y,
    const float* seg_origin_z,
    const float* seg_dir_x,
    const float* seg_dir_y,
    const float* seg_dir_z,
    const float* blocker_dist,
    const float* seg_field_re,
    const float* seg_field_im,
    const float* seg_vec_x_re,
    const float* seg_vec_x_im,
    const float* seg_vec_y_re,
    const float* seg_vec_y_im,
    const float* seg_vec_z_re,
    const float* seg_vec_z_im,
    const float* trace_coord_0,
    const float* trace_coord_1,
    const float* trace_t,
    const float* trace_t_max_0,
    const float* trace_t_max_1,
    const int* tile_i0,
    const int* tile_i1,
    const int* tile_extent_0,
    const int* tile_extent_1,
    const float* t_seg_origin_x,
    const float* t_seg_origin_y,
    const float* t_seg_origin_z,
    const float* t_seg_field_re,
    const float* t_seg_field_im,
    const float* t_seg_vec_x_re,
    const float* t_seg_vec_x_im,
    const float* t_seg_vec_y_re,
    const float* t_seg_vec_y_im,
    const float* t_seg_vec_z_re,
    const float* t_seg_vec_z_im,
    float wavelength,
    float k,
    int n_rays,
    float* out_field_re,
    float* out_field_im,
    float* out_vec_x_re,
    float* out_vec_x_im,
    float* out_vec_y_re,
    float* out_vec_y_im,
    float* out_vec_z_re,
    float* out_vec_z_im
);

void suffix_grid_backward_resume_batched(
    int plane_axis,
    float plane_position,
    float coord_0_min,
    float coord_0_max,
    float coord_1_min,
    float coord_1_max,
    float cell_size_0,
    float cell_size_1,
    int n_coord_0,
    int n_coord_1,
    int max_steps,
    const float* coord_0,
    const float* coord_1,
    const int* active,
    const int* task_segment_idx,
    const float* seg_origin_x,
    const float* seg_origin_y,
    const float* seg_origin_z,
    const float* seg_dir_x,
    const float* seg_dir_y,
    const float* seg_dir_z,
    const float* blocker_dist,
    const float* seg_field_re,
    const float* seg_field_im,
    const float* seg_vec_x_re,
    const float* seg_vec_x_im,
    const float* seg_vec_y_re,
    const float* seg_vec_y_im,
    const float* seg_vec_z_re,
    const float* seg_vec_z_im,
    const float* trace_coord_0,
    const float* trace_coord_1,
    const float* trace_t,
    const float* trace_t_max_0,
    const float* trace_t_max_1,
    const int* tile_i0,
    const int* tile_i1,
    const int* tile_extent_0,
    const int* tile_extent_1,
    float wavelength,
    float k,
    int n_rays,
    const float* grad_field_re,
    const float* grad_field_im,
    const float* grad_vec_x_re,
    const float* grad_vec_x_im,
    const float* grad_vec_y_re,
    const float* grad_vec_y_im,
    const float* grad_vec_z_re,
    const float* grad_vec_z_im,
    float* grad_seg_origin_x,
    float* grad_seg_origin_y,
    float* grad_seg_origin_z,
    float* grad_seg_field_re,
    float* grad_seg_field_im,
    float* grad_seg_vec_x_re,
    float* grad_seg_vec_x_im,
    float* grad_seg_vec_y_re,
    float* grad_seg_vec_y_im,
    float* grad_seg_vec_z_re,
    float* grad_seg_vec_z_im
);

} // namespace witwin::channel::native_ext
