#pragma once

namespace witwin::channel::native_ext {

struct MaterialParams;

void utd_accumulate_tiled_forward_slots(
    const int* state_index,
    const int* rx_index,
    const int* valid_mask,
    const int* ownership_code,
    const float* const* state_slots,
    const float* rx_x,
    const float* rx_y,
    const float* rx_z,
    float* direct_re,
    float* direct_im,
    float* multi_re,
    float* multi_im,
    float* direct_vec_x_re,
    float* direct_vec_x_im,
    float* direct_vec_y_re,
    float* direct_vec_y_im,
    float* direct_vec_z_re,
    float* direct_vec_z_im,
    float* multi_vec_x_re,
    float* multi_vec_x_im,
    float* multi_vec_y_re,
    float* multi_vec_y_im,
    float* multi_vec_z_re,
    float* multi_vec_z_im,
    int n_local_states,
    int n_local_receivers,
    float k,
    MaterialParams material
);

void utd_accumulate_tiled_jvp_slots(
    const int* state_index,
    const int* rx_index,
    const int* valid_mask,
    const int* ownership_code,
    const float* const* state_slots,
    const float* rx_x,
    const float* rx_y,
    const float* rx_z,
    const float* const* tangent_slots,
    const float* tangent_rx_x,
    const float* tangent_rx_y,
    const float* tangent_rx_z,
    float* tangent_direct_vec_x_re,
    float* tangent_direct_vec_x_im,
    float* tangent_direct_vec_y_re,
    float* tangent_direct_vec_y_im,
    float* tangent_direct_vec_z_re,
    float* tangent_direct_vec_z_im,
    float* tangent_multi_vec_x_re,
    float* tangent_multi_vec_x_im,
    float* tangent_multi_vec_y_re,
    float* tangent_multi_vec_y_im,
    float* tangent_multi_vec_z_re,
    float* tangent_multi_vec_z_im,
    int n_local_states,
    int n_local_receivers,
    float k,
    MaterialParams material
);

void utd_accumulate_tiled_vjp_slots(
    const int* state_index,
    const int* rx_index,
    const int* valid_mask,
    const int* ownership_code,
    const float* const* state_slots,
    const float* rx_x,
    const float* rx_y,
    const float* rx_z,
    const float* grad_direct_vec_x_re,
    const float* grad_direct_vec_x_im,
    const float* grad_direct_vec_y_re,
    const float* grad_direct_vec_y_im,
    const float* grad_direct_vec_z_re,
    const float* grad_direct_vec_z_im,
    const float* grad_multi_vec_x_re,
    const float* grad_multi_vec_x_im,
    const float* grad_multi_vec_y_re,
    const float* grad_multi_vec_y_im,
    const float* grad_multi_vec_z_re,
    const float* grad_multi_vec_z_im,
    float* const* grad_state_slots,
    float* grad_rx_x,
    float* grad_rx_y,
    float* grad_rx_z,
    int n_local_states,
    int n_local_receivers,
    float k,
    MaterialParams material
);

void utd_pair_forward_slots(
    const int* state_index,
    const int* rx_index,
    const int* ownership_code,
    const float* const* state_slots,
    const float* rx_x,
    const float* rx_y,
    const float* rx_z,
    float* direct_re,
    float* direct_im,
    float* multi_re,
    float* multi_im,
    float* direct_vec_x_re,
    float* direct_vec_x_im,
    float* direct_vec_y_re,
    float* direct_vec_y_im,
    float* direct_vec_z_re,
    float* direct_vec_z_im,
    float* multi_vec_x_re,
    float* multi_vec_x_im,
    float* multi_vec_y_re,
    float* multi_vec_y_im,
    float* multi_vec_z_re,
    float* multi_vec_z_im,
    int n_pairs,
    float k,
    MaterialParams material
);

void utd_pair_jvp_slots(
    const int* state_index,
    const int* rx_index,
    const int* ownership_code,
    const float* const* state_slots,
    const float* rx_x,
    const float* rx_y,
    const float* rx_z,
    const float* const* tangent_slots,
    const float* tangent_rx_x,
    const float* tangent_rx_y,
    const float* tangent_rx_z,
    float* tangent_direct_re,
    float* tangent_direct_im,
    float* tangent_multi_re,
    float* tangent_multi_im,
    float* tangent_direct_vec_x_re,
    float* tangent_direct_vec_x_im,
    float* tangent_direct_vec_y_re,
    float* tangent_direct_vec_y_im,
    float* tangent_direct_vec_z_re,
    float* tangent_direct_vec_z_im,
    float* tangent_multi_vec_x_re,
    float* tangent_multi_vec_x_im,
    float* tangent_multi_vec_y_re,
    float* tangent_multi_vec_y_im,
    float* tangent_multi_vec_z_re,
    float* tangent_multi_vec_z_im,
    int n_pairs,
    float k,
    MaterialParams material
);

void utd_pair_vjp_slots(
    const int* state_index,
    const int* rx_index,
    const int* ownership_code,
    const float* const* state_slots,
    const float* rx_x,
    const float* rx_y,
    const float* rx_z,
    const float* grad_direct_re,
    const float* grad_direct_im,
    const float* grad_multi_re,
    const float* grad_multi_im,
    const float* grad_direct_vec_x_re,
    const float* grad_direct_vec_x_im,
    const float* grad_direct_vec_y_re,
    const float* grad_direct_vec_y_im,
    const float* grad_direct_vec_z_re,
    const float* grad_direct_vec_z_im,
    const float* grad_multi_vec_x_re,
    const float* grad_multi_vec_x_im,
    const float* grad_multi_vec_y_re,
    const float* grad_multi_vec_y_im,
    const float* grad_multi_vec_z_re,
    const float* grad_multi_vec_z_im,
    float* const* grad_state_slots,
    float* grad_rx_x,
    float* grad_rx_y,
    float* grad_rx_z,
    int n_pairs,
    float k,
    MaterialParams material
);

} // namespace witwin::channel::native_ext
