#pragma once

#include <cstdint>

namespace raydn {

struct DfrDirectAccumADParams {
    int n_rays;
    int state_count;
    int material_count;
    int grid_axis;
    float grid_position;
    float grid_coord0_min;
    float grid_coord0_max;
    float grid_coord1_min;
    float grid_coord1_max;
    int grid_resolution0;
    int grid_resolution1;
    float grid_cell_area;
    int direct_samples;
    int keller_samples;
    int suffix_samples;
    float wavelength;
    int seed;
    int n_triangles;

    const uint8_t *tape_active;
    const int *tape_state_idx;
    const int *tape_cell;
    const int *tape_material_idx;
    const float *tape_edge_u;

    const float *state_edge_pos_x;
    const float *state_edge_pos_y;
    const float *state_edge_pos_z;
    int state_edge_pos_stride;
    const float *state_edge_dir_x;
    const float *state_edge_dir_y;
    const float *state_edge_dir_z;
    int state_edge_dir_stride;
    const float *state_edge_t_min;
    int state_edge_t_min_stride;
    const float *state_edge_t_max;
    int state_edge_t_max_stride;
    const float *state_src_x;
    const float *state_src_y;
    const float *state_src_z;
    int state_src_stride;
    const float *state_wi_x;
    const float *state_wi_y;
    const float *state_wi_z;
    int state_wi_stride;
    const float *state_src_power;
    int state_src_power_stride;
    const float *state_exterior_angle;
    int state_exterior_angle_stride;
    const int *state_prim0;
    int state_prim0_stride;
    const int *state_prim1;
    int state_prim1_stride;
    const float *tri_p0_x;
    const float *tri_p0_y;
    const float *tri_p0_z;
    const float *tri_e1_x;
    const float *tri_e1_y;
    const float *tri_e1_z;
    const float *tri_e2_x;
    const float *tri_e2_y;
    const float *tri_e2_z;
    const float *tri_fn_x;
    const float *tri_fn_y;
    const float *tri_fn_z;
    const float *material_gain;
    int material_gain_stride;
    const uint8_t *material_valid;
    int material_valid_stride;

    const float *dot_state_edge_pos_x;
    const float *dot_state_edge_pos_y;
    const float *dot_state_edge_pos_z;
    int dot_state_edge_pos_stride;
    const float *dot_state_edge_dir_x;
    const float *dot_state_edge_dir_y;
    const float *dot_state_edge_dir_z;
    int dot_state_edge_dir_stride;
    const float *dot_state_edge_t_min;
    int dot_state_edge_t_min_stride;
    const float *dot_state_edge_t_max;
    int dot_state_edge_t_max_stride;
    const float *dot_state_src_x;
    const float *dot_state_src_y;
    const float *dot_state_src_z;
    int dot_state_src_stride;
    const float *dot_state_wi_x;
    const float *dot_state_wi_y;
    const float *dot_state_wi_z;
    int dot_state_wi_stride;
    const float *dot_state_src_power;
    int dot_state_src_power_stride;
    const float *dot_state_exterior_angle;
    int dot_state_exterior_angle_stride;
    const float *dot_material_gain;
    int dot_material_gain_stride;
    const float *dot_tri_p0_x;
    const float *dot_tri_p0_y;
    const float *dot_tri_p0_z;
    const float *dot_tri_fn_x;
    const float *dot_tri_fn_y;
    const float *dot_tri_fn_z;

    float *dot_out_power;
    float *dot_out_field_x_re;

    const float *grad_out_power;
    int grad_out_power_rank;
    int grad_out_power_stride0;
    int grad_out_power_stride1;
    const float *grad_out_field_x_re;
    int grad_out_field_x_re_rank;
    int grad_out_field_x_re_stride0;
    int grad_out_field_x_re_stride1;

    float *grad_state_edge_pos_x;
    float *grad_state_edge_pos_y;
    float *grad_state_edge_pos_z;
    int grad_state_edge_pos_stride;
    float *grad_state_edge_dir_x;
    float *grad_state_edge_dir_y;
    float *grad_state_edge_dir_z;
    int grad_state_edge_dir_stride;
    float *grad_state_edge_t_min;
    int grad_state_edge_t_min_stride;
    float *grad_state_edge_t_max;
    int grad_state_edge_t_max_stride;
    float *grad_state_src_x;
    float *grad_state_src_y;
    float *grad_state_src_z;
    int grad_state_src_stride;
    float *grad_state_wi_x;
    float *grad_state_wi_y;
    float *grad_state_wi_z;
    int grad_state_wi_stride;
    float *grad_state_src_power;
    int grad_state_src_power_stride;
    float *grad_state_exterior_angle;
    int grad_state_exterior_angle_stride;
    float *grad_material_gain;
    int grad_material_gain_stride;
    float *grad_tri_p0_x;
    float *grad_tri_p0_y;
    float *grad_tri_p0_z;
    float *grad_tri_fn_x;
    float *grad_tri_fn_y;
    float *grad_tri_fn_z;
};

void dfr_direct_accum_jvp_gpu(const DfrDirectAccumADParams &params);
void dfr_direct_accum_vjp_gpu(const DfrDirectAccumADParams &params);

struct DfrChainAccumADParams {
    int n_rays;
    int state_count;
    int recursive_state_count;
    int material_count;
    int grid_axis;
    float grid_position;
    float grid_coord0_min;
    float grid_coord0_max;
    float grid_coord1_min;
    float grid_coord1_max;
    int grid_resolution0;
    int grid_resolution1;
    float grid_cell_area;
    int direct_samples;
    int keller_samples;
    int suffix_samples;
    int max_order;
    float wavelength;
    int seed;
    int n_triangles;

    const uint8_t *tape_active;
    const int *tape_cell;

    const int *state_edge_index;
    int state_edge_index_stride;
    const float *state_edge_pos_x;
    const float *state_edge_pos_y;
    const float *state_edge_pos_z;
    int state_edge_pos_stride;
    const float *state_edge_dir_x;
    const float *state_edge_dir_y;
    const float *state_edge_dir_z;
    int state_edge_dir_stride;
    const float *state_edge_t_min;
    int state_edge_t_min_stride;
    const float *state_edge_t_max;
    int state_edge_t_max_stride;
    const float *state_src_x;
    const float *state_src_y;
    const float *state_src_z;
    int state_src_stride;
    const float *state_src_power;
    int state_src_power_stride;
    const float *state_exterior_angle;
    int state_exterior_angle_stride;
    const int *state_prim0;
    int state_prim0_stride;
    const int *state_prim1;
    int state_prim1_stride;

    const int *recursive_state_edge_index;
    int recursive_state_edge_index_stride;
    const float *recursive_state_edge_pos_x;
    const float *recursive_state_edge_pos_y;
    const float *recursive_state_edge_pos_z;
    int recursive_state_edge_pos_stride;
    const float *recursive_state_edge_dir_x;
    const float *recursive_state_edge_dir_y;
    const float *recursive_state_edge_dir_z;
    int recursive_state_edge_dir_stride;
    const float *recursive_state_edge_t_min;
    int recursive_state_edge_t_min_stride;
    const float *recursive_state_edge_t_max;
    int recursive_state_edge_t_max_stride;
    const float *recursive_state_exterior_angle;
    int recursive_state_exterior_angle_stride;
    const int *recursive_state_prim0;
    int recursive_state_prim0_stride;
    const int *recursive_state_prim1;
    int recursive_state_prim1_stride;

    const float *tri_p0_x;
    const float *tri_p0_y;
    const float *tri_p0_z;
    const float *tri_e1_x;
    const float *tri_e1_y;
    const float *tri_e1_z;
    const float *tri_e2_x;
    const float *tri_e2_y;
    const float *tri_e2_z;
    const float *tri_fn_x;
    const float *tri_fn_y;
    const float *tri_fn_z;

    const float *material_gain;
    int material_gain_stride;
    const uint8_t *material_valid;
    int material_valid_stride;

    const float *dot_state_edge_pos_x;
    const float *dot_state_edge_pos_y;
    const float *dot_state_edge_pos_z;
    int dot_state_edge_pos_stride;
    const float *dot_state_edge_dir_x;
    const float *dot_state_edge_dir_y;
    const float *dot_state_edge_dir_z;
    int dot_state_edge_dir_stride;
    const float *dot_state_edge_t_min;
    int dot_state_edge_t_min_stride;
    const float *dot_state_edge_t_max;
    int dot_state_edge_t_max_stride;
    const float *dot_state_src_x;
    const float *dot_state_src_y;
    const float *dot_state_src_z;
    int dot_state_src_stride;
    const float *dot_state_src_power;
    int dot_state_src_power_stride;
    const float *dot_state_exterior_angle;
    int dot_state_exterior_angle_stride;

    const float *dot_recursive_state_edge_pos_x;
    const float *dot_recursive_state_edge_pos_y;
    const float *dot_recursive_state_edge_pos_z;
    int dot_recursive_state_edge_pos_stride;
    const float *dot_recursive_state_edge_dir_x;
    const float *dot_recursive_state_edge_dir_y;
    const float *dot_recursive_state_edge_dir_z;
    int dot_recursive_state_edge_dir_stride;
    const float *dot_recursive_state_edge_t_min;
    int dot_recursive_state_edge_t_min_stride;
    const float *dot_recursive_state_edge_t_max;
    int dot_recursive_state_edge_t_max_stride;
    const float *dot_recursive_state_exterior_angle;
    int dot_recursive_state_exterior_angle_stride;
    const float *dot_material_gain;
    int dot_material_gain_stride;
    const float *dot_tri_p0_x;
    const float *dot_tri_p0_y;
    const float *dot_tri_p0_z;
    const float *dot_tri_fn_x;
    const float *dot_tri_fn_y;
    const float *dot_tri_fn_z;

    float *dot_out_power;
    float *dot_out_field_x_re;

    const float *grad_out_power;
    int grad_out_power_rank;
    int grad_out_power_stride0;
    int grad_out_power_stride1;
    const float *grad_out_field_x_re;
    int grad_out_field_x_re_rank;
    int grad_out_field_x_re_stride0;
    int grad_out_field_x_re_stride1;

    float *grad_state_edge_pos_x;
    float *grad_state_edge_pos_y;
    float *grad_state_edge_pos_z;
    int grad_state_edge_pos_stride;
    float *grad_state_edge_dir_x;
    float *grad_state_edge_dir_y;
    float *grad_state_edge_dir_z;
    int grad_state_edge_dir_stride;
    float *grad_state_edge_t_min;
    int grad_state_edge_t_min_stride;
    float *grad_state_edge_t_max;
    int grad_state_edge_t_max_stride;
    float *grad_state_src_x;
    float *grad_state_src_y;
    float *grad_state_src_z;
    int grad_state_src_stride;
    float *grad_state_src_power;
    int grad_state_src_power_stride;
    float *grad_state_exterior_angle;
    int grad_state_exterior_angle_stride;

    float *grad_recursive_state_edge_pos_x;
    float *grad_recursive_state_edge_pos_y;
    float *grad_recursive_state_edge_pos_z;
    int grad_recursive_state_edge_pos_stride;
    float *grad_recursive_state_edge_dir_x;
    float *grad_recursive_state_edge_dir_y;
    float *grad_recursive_state_edge_dir_z;
    int grad_recursive_state_edge_dir_stride;
    float *grad_recursive_state_edge_t_min;
    int grad_recursive_state_edge_t_min_stride;
    float *grad_recursive_state_edge_t_max;
    int grad_recursive_state_edge_t_max_stride;
    float *grad_recursive_state_exterior_angle;
    int grad_recursive_state_exterior_angle_stride;
    float *grad_material_gain;
    int grad_material_gain_stride;
    float *grad_tri_p0_x;
    float *grad_tri_p0_y;
    float *grad_tri_p0_z;
    float *grad_tri_fn_x;
    float *grad_tri_fn_y;
    float *grad_tri_fn_z;
};

void dfr_chain_accum_jvp_gpu(const DfrChainAccumADParams &params);
void dfr_chain_accum_vjp_gpu(const DfrChainAccumADParams &params);

} // namespace raydn

