#include <torch/extension.h>

#include "registry.h"

#include <cstdint>
#include <string>
#include <vector>

std::vector<at::Tensor> cn_coupled_rd_prepare_cuda(
    at::Tensor source,
    at::Tensor receiver,
    at::Tensor plane_point,
    at::Tensor plane_normal,
    at::Tensor edge_pos,
    at::Tensor edge_dir,
    at::Tensor edge_t_min,
    at::Tensor edge_t_max);
pybind11::dict cn_coupled_rd_prepare_backward(
    at::Tensor source,
    at::Tensor receiver,
    at::Tensor plane_point,
    at::Tensor plane_normal,
    at::Tensor edge_pos,
    at::Tensor edge_dir,
    at::Tensor edge_t_min,
    pybind11::object grad_edge_point,
    pybind11::object grad_reflection_point,
    bool need_grad_source,
    bool need_grad_receiver);
pybind11::dict cn_coupled_rd_prepare_jvp(
    at::Tensor source,
    at::Tensor receiver,
    at::Tensor plane_point,
    at::Tensor plane_normal,
    at::Tensor edge_pos,
    at::Tensor edge_dir,
    at::Tensor edge_t_min,
    pybind11::object tangent_source,
    pybind11::object tangent_receiver);
pybind11::dict cn_field_diffraction_wedge(
    at::Tensor source,
    at::Tensor target,
    at::Tensor edge_position,
    at::Tensor edge_direction,
    at::Tensor edge_t_min,
    at::Tensor edge_t_max,
    at::Tensor edge_n0,
    at::Tensor edge_n1,
    at::Tensor exterior_angle,
    at::Tensor face0_valid,
    at::Tensor face0_eps_r,
    at::Tensor face0_sigma_e,
    at::Tensor face0_mu_r,
    at::Tensor face0_gain,
    at::Tensor face1_valid,
    at::Tensor face1_eps_r,
    at::Tensor face1_sigma_e,
    at::Tensor face1_mu_r,
    at::Tensor face1_gain,
    at::Tensor tx_power,
    double frequency_hz,
    pybind11::object vertex_v0,
    pybind11::object vertex_v1,
    pybind11::object vertex_opp0,
    pybind11::object vertex_opp1,
    pybind11::object edge_boundary);
pybind11::dict cn_field_diffraction_wedge_backward(
    at::Tensor source,
    at::Tensor target,
    at::Tensor edge_position,
    at::Tensor edge_direction,
    at::Tensor edge_t_min,
    at::Tensor edge_t_max,
    at::Tensor edge_n0,
    at::Tensor edge_n1,
    at::Tensor exterior_angle,
    at::Tensor face0_valid,
    at::Tensor face0_eps_r,
    at::Tensor face0_sigma_e,
    at::Tensor face0_mu_r,
    at::Tensor face0_gain,
    at::Tensor face1_valid,
    at::Tensor face1_eps_r,
    at::Tensor face1_sigma_e,
    at::Tensor face1_mu_r,
    at::Tensor face1_gain,
    at::Tensor tx_power,
    double frequency_hz,
    pybind11::object vertex_v0,
    pybind11::object vertex_v1,
    pybind11::object vertex_opp0,
    pybind11::object vertex_opp1,
    pybind11::object edge_boundary,
    pybind11::object grad_field_vector,
    pybind11::object grad_direction,
    bool need_grad_material,
    bool need_grad_frequency,
    bool need_grad_geometry,
    bool need_grad_vertices);
pybind11::dict cn_field_diffraction_wedge_jvp(
    at::Tensor source,
    at::Tensor target,
    at::Tensor edge_position,
    at::Tensor edge_direction,
    at::Tensor edge_t_min,
    at::Tensor edge_t_max,
    at::Tensor edge_n0,
    at::Tensor edge_n1,
    at::Tensor exterior_angle,
    at::Tensor face0_valid,
    at::Tensor face0_eps_r,
    at::Tensor face0_sigma_e,
    at::Tensor face0_mu_r,
    at::Tensor face0_gain,
    at::Tensor face1_valid,
    at::Tensor face1_eps_r,
    at::Tensor face1_sigma_e,
    at::Tensor face1_mu_r,
    at::Tensor face1_gain,
    at::Tensor tx_power,
    double frequency_hz,
    pybind11::object vertex_v0,
    pybind11::object vertex_v1,
    pybind11::object vertex_opp0,
    pybind11::object vertex_opp1,
    pybind11::object edge_boundary,
    pybind11::object tangent_source,
    pybind11::object tangent_target,
    pybind11::object tangent_face0_eps_r,
    pybind11::object tangent_face0_sigma_e,
    pybind11::object tangent_face0_gain,
    pybind11::object tangent_face1_eps_r,
    pybind11::object tangent_face1_sigma_e,
    pybind11::object tangent_face1_gain,
    double tangent_frequency,
    pybind11::object tangent_vertex_v0,
    pybind11::object tangent_vertex_v1,
    pybind11::object tangent_vertex_opp0,
    pybind11::object tangent_vertex_opp1);
pybind11::dict cn_field_coupled_rd_backward(
    at::Tensor source,
    at::Tensor target,
    at::Tensor reflection_position,
    at::Tensor reflection_normal,
    at::Tensor edge_position,
    at::Tensor edge_direction,
    at::Tensor edge_n0,
    at::Tensor edge_n1,
    at::Tensor exterior_angle,
    at::Tensor tx_power,
    at::Tensor tx_polarization,
    at::Tensor rx_polarization,
    at::Tensor reflection_eps_r,
    at::Tensor reflection_sigma_e,
    at::Tensor reflection_mu_r,
    at::Tensor reflection_gain,
    at::Tensor reflection_thickness,
    at::Tensor wedge_eps_r0,
    at::Tensor wedge_sigma_e0,
    at::Tensor wedge_mu_r0,
    at::Tensor wedge_gain0,
    at::Tensor wedge_thickness0,
    at::Tensor wedge_eps_r1,
    at::Tensor wedge_sigma_e1,
    at::Tensor wedge_mu_r1,
    at::Tensor wedge_gain1,
    at::Tensor wedge_thickness1,
    at::Tensor edge_line_min,
    at::Tensor edge_line_max,
    double frequency_hz,
    bool reverse,
    pybind11::object grad_field_vector,
    pybind11::object grad_coefficient,
    pybind11::object grad_path_field,
    pybind11::object grad_path_gain,
    bool need_grad_eps_r,
    bool need_grad_sigma_e,
    bool need_grad_gain,
    bool need_grad_thickness,
    bool need_grad_frequency,
    bool need_grad_geometry);
pybind11::dict cn_field_coupled_rd_jvp(
    at::Tensor source,
    at::Tensor target,
    at::Tensor reflection_position,
    at::Tensor reflection_normal,
    at::Tensor edge_position,
    at::Tensor edge_direction,
    at::Tensor edge_n0,
    at::Tensor edge_n1,
    at::Tensor exterior_angle,
    at::Tensor tx_power,
    at::Tensor tx_polarization,
    at::Tensor rx_polarization,
    at::Tensor reflection_eps_r,
    at::Tensor reflection_sigma_e,
    at::Tensor reflection_mu_r,
    at::Tensor reflection_gain,
    at::Tensor reflection_thickness,
    at::Tensor wedge_eps_r0,
    at::Tensor wedge_sigma_e0,
    at::Tensor wedge_mu_r0,
    at::Tensor wedge_gain0,
    at::Tensor wedge_thickness0,
    at::Tensor wedge_eps_r1,
    at::Tensor wedge_sigma_e1,
    at::Tensor wedge_mu_r1,
    at::Tensor wedge_gain1,
    at::Tensor wedge_thickness1,
    at::Tensor edge_line_min,
    at::Tensor edge_line_max,
    double frequency_hz,
    bool reverse,
    pybind11::object tangent_source,
    pybind11::object tangent_target,
    pybind11::object tangent_reflection_position,
    pybind11::object tangent_edge_position,
    pybind11::object tangent_eps_r,
    pybind11::object tangent_sigma_e,
    pybind11::object tangent_gain,
    pybind11::object tangent_thickness,
    double tangent_frequency);
pybind11::dict cn_field_project_complex3_backward(
    at::Tensor field_vector,
    at::Tensor direction,
    at::Tensor rx_polarization,
    pybind11::object grad_coefficient,
    pybind11::object grad_path_gain,
    bool need_grad_field_vector,
    bool need_grad_direction);
pybind11::dict cn_field_project_complex3_jvp(
    at::Tensor field_vector,
    at::Tensor direction,
    at::Tensor rx_polarization,
    pybind11::object tangent_field_vector,
    pybind11::object tangent_direction);
pybind11::dict cn_field_free_space(
    torch::Tensor source,
    torch::Tensor target,
    torch::Tensor tx_power,
    torch::Tensor tx_polarization,
    torch::Tensor rx_polarization,
    double frequency_hz);
pybind11::dict cn_field_project_complex3(
    torch::Tensor field_vector,
    torch::Tensor direction,
    torch::Tensor rx_polarization);
pybind11::dict cn_field_reflection_sequence(
    torch::Tensor source,
    torch::Tensor target,
    torch::Tensor interaction_positions,
    torch::Tensor interaction_normals,
    torch::Tensor tx_power,
    torch::Tensor tx_polarization,
    torch::Tensor rx_polarization,
    torch::Tensor eps_r,
    torch::Tensor sigma_e,
    torch::Tensor mu_r,
    torch::Tensor gain,
    torch::Tensor thickness,
    double frequency_hz);
pybind11::dict cn_field_transmission_sequence(
    torch::Tensor source,
    torch::Tensor target,
    torch::Tensor interaction_positions,
    torch::Tensor interaction_normals,
    torch::Tensor interaction_material_id,
    torch::Tensor interaction_valid,
    torch::Tensor tx_power,
    torch::Tensor tx_polarization,
    torch::Tensor rx_polarization,
    torch::Tensor layer_offset,
    torch::Tensor layer_count,
    torch::Tensor layer_thickness_m,
    torch::Tensor layer_eps_r,
    torch::Tensor layer_sigma_e,
    torch::Tensor layer_mu_r,
    double frequency_hz);
pybind11::dict cn_field_free_space_fwd64(
    torch::Tensor source,
    torch::Tensor target,
    torch::Tensor tx_power,
    torch::Tensor tx_polarization,
    torch::Tensor rx_polarization,
    double frequency_hz);
pybind11::dict cn_field_free_space_backward(
    torch::Tensor source,
    torch::Tensor target,
    torch::Tensor tx_power,
    torch::Tensor tx_polarization,
    torch::Tensor rx_polarization,
    double frequency_hz,
    pybind11::object grad_field_vector,
    pybind11::object grad_coefficient,
    pybind11::object grad_path_field,
    pybind11::object grad_path_gain,
    pybind11::object grad_path_length,
    pybind11::object grad_delay,
    bool need_grad_frequency,
    bool need_grad_geometry);
pybind11::dict cn_field_free_space_jvp(
    torch::Tensor source,
    torch::Tensor target,
    torch::Tensor tx_power,
    torch::Tensor tx_polarization,
    torch::Tensor rx_polarization,
    double frequency_hz,
    double tangent_frequency,
    pybind11::object tangent_source,
    pybind11::object tangent_target);
pybind11::dict cn_field_reflection_sequence_backward(
    torch::Tensor source,
    torch::Tensor target,
    torch::Tensor interaction_positions,
    torch::Tensor interaction_normals,
    torch::Tensor tx_power,
    torch::Tensor tx_polarization,
    torch::Tensor rx_polarization,
    torch::Tensor eps_r,
    torch::Tensor sigma_e,
    torch::Tensor mu_r,
    torch::Tensor gain,
    torch::Tensor thickness,
    double frequency_hz,
    pybind11::object grad_field_vector,
    pybind11::object grad_coefficient,
    pybind11::object grad_path_field,
    pybind11::object grad_path_gain,
    pybind11::object grad_path_length,
    pybind11::object grad_delay,
    bool need_grad_eps_r,
    bool need_grad_sigma_e,
    bool need_grad_gain,
    bool need_grad_thickness,
    bool need_grad_frequency,
    bool need_grad_geometry);
pybind11::dict cn_field_reflection_sequence_jvp(
    torch::Tensor source,
    torch::Tensor target,
    torch::Tensor interaction_positions,
    torch::Tensor interaction_normals,
    torch::Tensor tx_power,
    torch::Tensor tx_polarization,
    torch::Tensor rx_polarization,
    torch::Tensor eps_r,
    torch::Tensor sigma_e,
    torch::Tensor mu_r,
    torch::Tensor gain,
    torch::Tensor thickness,
    double frequency_hz,
    pybind11::object tangent_eps_r,
    pybind11::object tangent_sigma_e,
    pybind11::object tangent_gain,
    pybind11::object tangent_thickness,
    double tangent_frequency,
    pybind11::object tangent_source,
    pybind11::object tangent_target,
    pybind11::object tangent_interaction_positions,
    pybind11::object tangent_interaction_normals);
pybind11::dict cn_field_transmission_sequence_backward(
    torch::Tensor source,
    torch::Tensor target,
    torch::Tensor interaction_positions,
    torch::Tensor interaction_normals,
    torch::Tensor interaction_material_id,
    torch::Tensor interaction_valid,
    torch::Tensor tx_power,
    torch::Tensor tx_polarization,
    torch::Tensor rx_polarization,
    torch::Tensor layer_offset,
    torch::Tensor layer_count,
    torch::Tensor layer_thickness_m,
    torch::Tensor layer_eps_r,
    torch::Tensor layer_sigma_e,
    torch::Tensor layer_mu_r,
    double frequency_hz,
    pybind11::object grad_field_vector,
    pybind11::object grad_coefficient,
    pybind11::object grad_path_field,
    pybind11::object grad_path_gain,
    pybind11::object grad_path_length,
    pybind11::object grad_delay,
    bool need_grad_layer_thickness,
    bool need_grad_layer_eps_r,
    bool need_grad_layer_sigma_e,
    bool need_grad_frequency,
    bool need_grad_geometry);
pybind11::dict cn_field_transmission_sequence_jvp(
    torch::Tensor source,
    torch::Tensor target,
    torch::Tensor interaction_positions,
    torch::Tensor interaction_normals,
    torch::Tensor interaction_material_id,
    torch::Tensor interaction_valid,
    torch::Tensor tx_power,
    torch::Tensor tx_polarization,
    torch::Tensor rx_polarization,
    torch::Tensor layer_offset,
    torch::Tensor layer_count,
    torch::Tensor layer_thickness_m,
    torch::Tensor layer_eps_r,
    torch::Tensor layer_sigma_e,
    torch::Tensor layer_mu_r,
    double frequency_hz,
    pybind11::object tangent_layer_thickness_m,
    pybind11::object tangent_layer_eps_r,
    pybind11::object tangent_layer_sigma_e,
    double tangent_frequency,
    pybind11::object tangent_source,
    pybind11::object tangent_target,
    pybind11::object tangent_interaction_positions,
    pybind11::object tangent_interaction_normals);
pybind11::dict cn_field_coupled_rd(
    torch::Tensor source,
    torch::Tensor target,
    torch::Tensor reflection_position,
    torch::Tensor reflection_normal,
    torch::Tensor edge_position,
    torch::Tensor edge_direction,
    torch::Tensor edge_n0,
    torch::Tensor edge_n1,
    torch::Tensor exterior_angle,
    torch::Tensor tx_power,
    torch::Tensor tx_polarization,
    torch::Tensor rx_polarization,
    torch::Tensor reflection_eps_r,
    torch::Tensor reflection_sigma_e,
    torch::Tensor reflection_mu_r,
    torch::Tensor reflection_gain,
    torch::Tensor reflection_thickness,
    torch::Tensor wedge_eps_r0,
    torch::Tensor wedge_sigma_e0,
    torch::Tensor wedge_mu_r0,
    torch::Tensor wedge_gain0,
    torch::Tensor wedge_thickness0,
    torch::Tensor wedge_eps_r1,
    torch::Tensor wedge_sigma_e1,
    torch::Tensor wedge_mu_r1,
    torch::Tensor wedge_gain1,
    torch::Tensor wedge_thickness1,
    torch::Tensor edge_line_min,
    torch::Tensor edge_line_max,
    double frequency_hz,
    bool reverse);

void register_fields(pybind11::module_ &module) {
    module.def(
        "field_free_space",
        &cn_field_free_space,
        "Evaluate the canonical complex3 free-space field and receiver projection.");
    module.def(
        "field_project_complex3",
        &cn_field_project_complex3,
        "Project a world-Cartesian complex3 field onto a receiver polarization.");
    module.def(
        "field_reflection_sequence",
        &cn_field_reflection_sequence,
        "Transport a canonical complex3 field through a finite-slab reflection sequence.");
    module.def(
        "field_transmission_sequence",
        &cn_field_transmission_sequence,
        "Transport a canonical complex3 field through a thin_sheet transmission sequence.");
    module.def(
        "field_coupled_rd",
        &cn_field_coupled_rd,
        "Transport a canonical complex3 field through coupled R-D or D-R events.");
    module.def(
        "field_free_space_fwd64",
        &cn_field_free_space_fwd64,
        "Float64 free-space field forward for the strict gradcheck AD path.");
    module.def(
        "field_free_space_backward",
        &cn_field_free_space_backward,
        "Fixed-topology VJP of the free-space field (frequency and endpoints).");
    module.def(
        "field_free_space_jvp",
        &cn_field_free_space_jvp,
        "Fixed-topology JVP of the free-space field (frequency and endpoints).");
    module.def(
        "field_reflection_sequence_backward",
        &cn_field_reflection_sequence_backward,
        "Fixed-topology VJP of the reflection sequence (materials, frequency, geometry).");
    module.def(
        "field_reflection_sequence_jvp",
        &cn_field_reflection_sequence_jvp,
        "Fixed-topology JVP of the reflection sequence (materials, frequency, geometry).");
    module.def(
        "field_transmission_sequence_backward",
        &cn_field_transmission_sequence_backward,
        "Fixed-topology VJP of the transmission sequence (CSR layers, frequency, geometry).");
    module.def(
        "field_transmission_sequence_jvp",
        &cn_field_transmission_sequence_jvp,
        "Fixed-topology JVP of the transmission sequence (CSR layers, frequency, geometry).");
    module.def(
        "field_diffraction_wedge",
        &cn_field_diffraction_wedge,
        "Re-evaluate RayD's order-1 UTD wedge field from the frozen topology (plan 07 AD-4).");
    module.def(
        "field_diffraction_wedge_backward",
        &cn_field_diffraction_wedge_backward,
        "Fixed-topology VJP of the wedge field (face materials, frequency, endpoints).");
    module.def(
        "field_diffraction_wedge_jvp",
        &cn_field_diffraction_wedge_jvp,
        "Fixed-topology JVP of the wedge field (face materials, frequency, endpoints).");
    module.def(
        "field_coupled_rd_backward",
        &cn_field_coupled_rd_backward,
        "Fixed-topology VJP of the coupled R-D field (12 material scalars, frequency, geometry).");
    module.def(
        "field_coupled_rd_jvp",
        &cn_field_coupled_rd_jvp,
        "Fixed-topology JVP of the coupled R-D field (12 material scalars, frequency, geometry).");
    module.def(
        "field_project_complex3_backward",
        &cn_field_project_complex3_backward,
        "VJP of the receiver projection (field vector and arrival direction).");
    module.def(
        "field_project_complex3_jvp",
        &cn_field_project_complex3_jvp,
        "JVP of the receiver projection (field vector and arrival direction).");
    module.def(
        "coupled_rd_prepare",
        &cn_coupled_rd_prepare_cuda,
        "Fixed-winner coupled stationary geometry re-solve (image source, edge point, wall crossing).");
    module.def(
        "coupled_rd_prepare_backward",
        &cn_coupled_rd_prepare_backward,
        "VJP of the coupled stationary geometry re-solve (endpoints).");
    module.def(
        "coupled_rd_prepare_jvp",
        &cn_coupled_rd_prepare_jvp,
        "JVP of the coupled stationary geometry re-solve (endpoints).");
}
