#include <torch/extension.h>

#include "registry.h"

#include <cstdint>
#include <string>
#include <vector>

pybind11::dict cn_em_layer_stack_eval(
    torch::Tensor cos_theta,
    torch::Tensor material_id,
    torch::Tensor layer_offset,
    torch::Tensor layer_count,
    torch::Tensor layer_thickness_m,
    torch::Tensor layer_eps_r,
    torch::Tensor layer_sigma_e,
    torch::Tensor layer_mu_r,
    double frequency_hz);
pybind11::dict cn_em_layer_stack_backward(
    torch::Tensor cos_theta,
    torch::Tensor material_id,
    torch::Tensor layer_offset,
    torch::Tensor layer_count,
    torch::Tensor layer_thickness_m,
    torch::Tensor layer_eps_r,
    torch::Tensor layer_sigma_e,
    torch::Tensor layer_mu_r,
    double frequency_hz,
    pybind11::sequence grad_outputs,
    bool need_cos_theta,
    bool need_layers,
    bool need_frequency);
pybind11::dict cn_em_layer_stack_jvp(
    torch::Tensor cos_theta,
    torch::Tensor material_id,
    torch::Tensor layer_offset,
    torch::Tensor layer_count,
    torch::Tensor layer_thickness_m,
    torch::Tensor layer_eps_r,
    torch::Tensor layer_sigma_e,
    torch::Tensor layer_mu_r,
    double frequency_hz,
    pybind11::object tangent_cos_theta,
    pybind11::object tangent_layer_thickness,
    pybind11::object tangent_layer_eps_r,
    pybind11::object tangent_layer_sigma_e,
    double tangent_frequency);
pybind11::dict cn_scattering_table_eval(
    torch::Tensor wi, torch::Tensor wo, torch::Tensor f_te, torch::Tensor f_tm);
torch::Tensor cn_scattering_table_pdf(
    torch::Tensor wi, torch::Tensor wo, torch::Tensor sample_density, bool reverse);
pybind11::dict cn_scattering_table_sample(
    torch::Tensor wi,
    torch::Tensor uniforms,
    torch::Tensor marginal_cdf,
    torch::Tensor conditional_cdf,
    torch::Tensor sample_density);
pybind11::dict cn_scattering_event_probabilities(
    torch::Tensor cos_theta,
    torch::Tensor material_id,
    torch::Tensor cap_r_te,
    torch::Tensor cap_r_tm,
    torch::Tensor cap_t_te,
    torch::Tensor cap_t_tm,
    torch::Tensor rough_sigma_h_m,
    torch::Tensor scatter_model_id,
    double frequency_hz,
    double probability_floor);
pybind11::dict cn_scattering_patch_integral_eval(
    torch::Tensor patch_tris,
    torch::Tensor patch_uvs,
    torch::Tensor rows,
    torch::Tensor d_i,
    torch::Tensor d_o,
    torch::Tensor n_rows,
    torch::Tensor r_te,
    torch::Tensor r_tm,
    torch::Tensor pol_t,
    torch::Tensor pol_r,
    torch::Tensor r1_rows,
    torch::Tensor r2_rows,
    torch::Tensor centroids,
    torch::Tensor heights,
    torch::Tensor quad_a,
    torch::Tensor quad_b,
    torch::Tensor quad_w,
    double k0);
pybind11::dict cn_scattering_ensemble_eval(
    torch::Tensor wo_rows,
    torch::Tensor r2_rows,
    torch::Tensor cos_o_rows,
    torch::Tensor n_o,
    torch::Tensor t1r,
    torch::Tensor t2r,
    torch::Tensor wi_local,
    torch::Tensor cos_i,
    torch::Tensor r1,
    torch::Tensor a_te2,
    torch::Tensor a_tm2,
    torch::Tensor weights,
    torch::Tensor material_id,
    torch::Tensor backup_axis,
    torch::Tensor rx_pol,
    torch::Tensor rc_idx,
    torch::Tensor sc_idx,
    torch::Tensor fte_flat,
    torch::Tensor ftm_flat,
    torch::Tensor table_offset,
    torch::Tensor table_dims,
    torch::Tensor material_slot,
    double coef,
    double threshold);
pybind11::dict cn_scattering_ensemble_eval_backward(
    torch::Tensor wo_rows,
    torch::Tensor r2_rows,
    torch::Tensor cos_o_rows,
    torch::Tensor n_o,
    torch::Tensor t1r,
    torch::Tensor t2r,
    torch::Tensor wi_local,
    torch::Tensor cos_i,
    torch::Tensor r1,
    torch::Tensor a_te2,
    torch::Tensor a_tm2,
    torch::Tensor weights,
    torch::Tensor material_id,
    torch::Tensor backup_axis,
    torch::Tensor rx_pol,
    torch::Tensor rc_idx,
    torch::Tensor sc_idx,
    torch::Tensor fte_flat,
    torch::Tensor ftm_flat,
    torch::Tensor table_offset,
    torch::Tensor table_dims,
    torch::Tensor material_slot,
    double coef,
    double threshold,
    pybind11::object grad_gain,
    pybind11::object grad_amplitude,
    pybind11::object grad_length,
    bool need_grad_rows,
    bool need_grad_samples,
    bool need_grad_tables,
    bool need_grad_coef);
pybind11::dict cn_scattering_ensemble_eval_jvp(
    torch::Tensor wo_rows,
    torch::Tensor r2_rows,
    torch::Tensor cos_o_rows,
    torch::Tensor n_o,
    torch::Tensor t1r,
    torch::Tensor t2r,
    torch::Tensor wi_local,
    torch::Tensor cos_i,
    torch::Tensor r1,
    torch::Tensor a_te2,
    torch::Tensor a_tm2,
    torch::Tensor weights,
    torch::Tensor material_id,
    torch::Tensor backup_axis,
    torch::Tensor rx_pol,
    torch::Tensor rc_idx,
    torch::Tensor sc_idx,
    torch::Tensor fte_flat,
    torch::Tensor ftm_flat,
    torch::Tensor table_offset,
    torch::Tensor table_dims,
    torch::Tensor material_slot,
    double coef,
    double threshold,
    pybind11::object t_wo_rows,
    pybind11::object t_r2_rows,
    pybind11::object t_cos_o_rows,
    pybind11::object t_n_o,
    pybind11::object t_t1r,
    pybind11::object t_t2r,
    pybind11::object t_wi_local,
    pybind11::object t_cos_i,
    pybind11::object t_r1,
    pybind11::object t_a_te2,
    pybind11::object t_a_tm2,
    pybind11::object t_weights,
    pybind11::object t_fte_flat,
    pybind11::object t_ftm_flat,
    double tangent_coef);
pybind11::dict cn_scattering_patch_integral_eval_backward(
    torch::Tensor patch_tris,
    torch::Tensor patch_uvs,
    torch::Tensor rows,
    torch::Tensor d_i,
    torch::Tensor d_o,
    torch::Tensor n_rows,
    torch::Tensor r_te,
    torch::Tensor r_tm,
    torch::Tensor pol_t,
    torch::Tensor pol_r,
    torch::Tensor r1_rows,
    torch::Tensor r2_rows,
    torch::Tensor centroids,
    torch::Tensor heights,
    torch::Tensor quad_a,
    torch::Tensor quad_b,
    torch::Tensor quad_w,
    double k0,
    torch::Tensor grad_total,
    bool need_grad_heights,
    bool need_grad_jones,
    bool need_grad_geometry,
    bool need_grad_k0);
pybind11::dict cn_scattering_patch_integral_eval_jvp(
    torch::Tensor patch_tris,
    torch::Tensor patch_uvs,
    torch::Tensor rows,
    torch::Tensor d_i,
    torch::Tensor d_o,
    torch::Tensor n_rows,
    torch::Tensor r_te,
    torch::Tensor r_tm,
    torch::Tensor pol_t,
    torch::Tensor pol_r,
    torch::Tensor r1_rows,
    torch::Tensor r2_rows,
    torch::Tensor centroids,
    torch::Tensor heights,
    torch::Tensor quad_a,
    torch::Tensor quad_b,
    torch::Tensor quad_w,
    double k0,
    pybind11::object t_heights,
    pybind11::object t_r_te,
    pybind11::object t_r_tm,
    pybind11::object t_d_i,
    pybind11::object t_d_o,
    pybind11::object t_r1_rows,
    pybind11::object t_r2_rows,
    pybind11::object t_centroids,
    double tangent_k0);

void register_materials(pybind11::module_ &module) {
    module.def(
        "em_layer_stack_eval",
        &cn_em_layer_stack_eval,
        "Evaluate shared em/ layer-stack reflection/transmission coefficients for parity tests.");
    module.def(
        "em_layer_stack_backward",
        &cn_em_layer_stack_backward,
        "Layer-stack VJP over cos_theta, CSR layer parameters and frequency (CUDA duals).");
    module.def(
        "em_layer_stack_jvp",
        &cn_em_layer_stack_jvp,
        "Layer-stack JVP over cos_theta, CSR layer parameters and frequency (CUDA duals).");
    module.def("scattering_table_eval", &cn_scattering_table_eval,
               "Evaluate a resident Kirchhoff BSDF table with native CUDA.");
    module.def("scattering_table_pdf", &cn_scattering_table_pdf,
               "Evaluate a resident Kirchhoff sampling PDF with native CUDA.");
    module.def("scattering_table_sample", &cn_scattering_table_sample,
               "Sample a resident Kirchhoff CDF table with native CUDA.");
    module.def("scattering_event_probabilities", &cn_scattering_event_probabilities,
               "Evaluate fused rough-surface event budgets with native CUDA.");
    module.def("scattering_ensemble_eval", &cn_scattering_ensemble_eval,
               "Evaluate the Kirchhoff ensemble scattering row physics with native CUDA (ADR-010 op 1).");
    module.def("scattering_patch_integral_eval", &cn_scattering_patch_integral_eval,
               "Evaluate the realization-coherent phase-screen patch integral with native CUDA (ADR-010 op 2).");
    module.def("scattering_ensemble_eval_backward", &cn_scattering_ensemble_eval_backward,
               "Fixed-topology VJP of the Kirchhoff ensemble scattering rows (rows, samples, tables, coef) (ADR-014).");
    module.def("scattering_ensemble_eval_jvp", &cn_scattering_ensemble_eval_jvp,
               "Fixed-topology JVP of the Kirchhoff ensemble scattering rows (rows, samples, tables, coef) (ADR-014).");
    module.def("scattering_patch_integral_eval_backward", &cn_scattering_patch_integral_eval_backward,
               "Fixed-topology VJP of the realization-coherent phase-screen patch integral (heights, jones, geometry, k0) (ADR-014).");
    module.def("scattering_patch_integral_eval_jvp", &cn_scattering_patch_integral_eval_jvp,
               "Fixed-topology JVP of the realization-coherent phase-screen patch integral (heights, jones, geometry, k0) (ADR-014).");
}
