#include "drjit_common.h"
#include <suffix_grid/bind.h>

#include <common/cuda_check.h>
#include <suffix_grid/suffix_grid.h>

void register_suffix_grid_bindings(nb::module_ &m) {
    m.def(
        "build_suffix_segment_tile_plan_raw",
        [](
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int tile_shape_0,
            int tile_shape_1,
            const DiffFloat &origin_0,
            const DiffFloat &origin_1,
            const DiffFloat &dir_0,
            const DiffFloat &dir_1,
            const DiffFloat &blocker_dist,
            const Int32 &active
        ) {
            using witwin::channel::native_ext::common::throw_cuda;

            const int n_segments = static_cast<int>(blocker_dist.size());
            DiffUInt32 segment_tile_counts = drjit::zeros<DiffUInt32>(static_cast<size_t>(n_segments));
            if (n_segments <= 0 || n_coord_0 <= 0 || n_coord_1 <= 0 || tile_shape_0 <= 0 || tile_shape_1 <= 0) {
                return nb::make_tuple(
                    segment_tile_counts,
                    drjit::zeros<DiffUInt32>(0),
                    drjit::zeros<DiffUInt32>(0),
                    drjit::zeros<DiffFloat>(0),
                    drjit::zeros<DiffFloat>(0),
                    drjit::zeros<DiffFloat>(0),
                    drjit::zeros<DiffFloat>(0),
                    drjit::zeros<DiffFloat>(0)
                );
            }

            const int max_steps = 2 * (n_coord_0 + n_coord_1);
            drjit::eval(origin_0, origin_1, dir_0, dir_1, blocker_dist, active, segment_tile_counts);

            witwin::channel::native_ext::suffix_segment_tile_plan_count(
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                tile_shape_0,
                tile_shape_1,
                max_steps,
                drjit_data_ptr(origin_0),
                drjit_data_ptr(origin_1),
                drjit_data_ptr(dir_0),
                drjit_data_ptr(dir_1),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(active),
                n_segments,
                drjit_data_ptr_mut(segment_tile_counts)
            );

            std::uint32_t *segment_offsets = nullptr;
            throw_cuda(
                cudaMalloc(&segment_offsets, static_cast<size_t>(n_segments) * sizeof(std::uint32_t)),
                "build_suffix_segment_tile_plan_raw cudaMalloc(segment_offsets)"
            );

            try {
                const std::uint32_t task_count = witwin::channel::native_ext::suffix_segment_tile_plan_scan(
                    drjit_data_ptr(segment_tile_counts),
                    n_segments,
                    segment_offsets
                );

                DiffUInt32 task_segment_idx = drjit::zeros<DiffUInt32>(static_cast<size_t>(task_count));
                DiffUInt32 task_tile_idx = drjit::zeros<DiffUInt32>(static_cast<size_t>(task_count));
                DiffFloat entry_coord_0 = drjit::zeros<DiffFloat>(static_cast<size_t>(task_count));
                DiffFloat entry_coord_1 = drjit::zeros<DiffFloat>(static_cast<size_t>(task_count));
                DiffFloat entry_t = drjit::zeros<DiffFloat>(static_cast<size_t>(task_count));
                DiffFloat entry_t_max_0 = drjit::zeros<DiffFloat>(static_cast<size_t>(task_count));
                DiffFloat entry_t_max_1 = drjit::zeros<DiffFloat>(static_cast<size_t>(task_count));

                drjit::eval(
                    task_segment_idx,
                    task_tile_idx,
                    entry_coord_0,
                    entry_coord_1,
                    entry_t,
                    entry_t_max_0,
                    entry_t_max_1
                );

                if (task_count > 0u) {
                    witwin::channel::native_ext::suffix_segment_tile_plan_write(
                        coord_0_min,
                        coord_0_max,
                        coord_1_min,
                        coord_1_max,
                        cell_size_0,
                        cell_size_1,
                        n_coord_0,
                        n_coord_1,
                        tile_shape_0,
                        tile_shape_1,
                        max_steps,
                        drjit_data_ptr(origin_0),
                        drjit_data_ptr(origin_1),
                        drjit_data_ptr(dir_0),
                        drjit_data_ptr(dir_1),
                        drjit_data_ptr(blocker_dist),
                        drjit_data_ptr(active),
                        n_segments,
                        segment_offsets,
                        drjit_data_ptr_mut(task_segment_idx),
                        drjit_data_ptr_mut(task_tile_idx),
                        drjit_data_ptr_mut(entry_coord_0),
                        drjit_data_ptr_mut(entry_coord_1),
                        drjit_data_ptr_mut(entry_t),
                        drjit_data_ptr_mut(entry_t_max_0),
                        drjit_data_ptr_mut(entry_t_max_1)
                    );
                }

                throw_cuda(cudaFree(segment_offsets), "build_suffix_segment_tile_plan_raw cudaFree(segment_offsets)");
                return nb::make_tuple(
                    segment_tile_counts,
                    task_segment_idx,
                    task_tile_idx,
                    entry_coord_0,
                    entry_coord_1,
                    entry_t,
                    entry_t_max_0,
                    entry_t_max_1
                );
            } catch (...) {
                cudaFree(segment_offsets);
                throw;
            }
        },
        "Build an exact reflected-suffix tile plan on the GPU using native CUDA DDA traversal."
    );

    m.def(
        "suffix_grid_forward_raw",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            const DiffFloat &coord_0,
            const DiffFloat &coord_1,
            const Int32 &active,
            const Int32 &task_segment_idx,
            const DiffFloat &seg_origin_x,
            const DiffFloat &seg_origin_y,
            const DiffFloat &seg_origin_z,
            const DiffFloat &seg_dir_x,
            const DiffFloat &seg_dir_y,
            const DiffFloat &seg_dir_z,
            const DiffFloat &blocker_dist,
            const DiffFloat &seg_field_re,
            const DiffFloat &seg_field_im,
            const DiffFloat &seg_vec_x_re,
            const DiffFloat &seg_vec_x_im,
            const DiffFloat &seg_vec_y_re,
            const DiffFloat &seg_vec_y_im,
            const DiffFloat &seg_vec_z_re,
            const DiffFloat &seg_vec_z_im,
            float wavelength,
            float k,
            int n_rays
        ) {
            size_t n_rx = static_cast<size_t>(n_coord_0) * static_cast<size_t>(n_coord_1);
            DiffFloat out_field_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_field_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_x_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_x_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_y_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_y_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_z_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_z_im = drjit::zeros<DiffFloat>(n_rx);

            drjit::eval(
                coord_0,
                coord_1,
                active,
                task_segment_idx,
                seg_origin_x,
                seg_origin_y,
                seg_origin_z,
                seg_dir_x,
                seg_dir_y,
                seg_dir_z,
                blocker_dist,
                seg_field_re,
                seg_field_im,
                seg_vec_x_re,
                seg_vec_x_im,
                seg_vec_y_re,
                seg_vec_y_im,
                seg_vec_z_re,
                seg_vec_z_im,
                out_field_re,
                out_field_im,
                out_vec_x_re,
                out_vec_x_im,
                out_vec_y_re,
                out_vec_y_im,
                out_vec_z_re,
                out_vec_z_im
            );

            witwin::channel::native_ext::suffix_grid_forward(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                drjit_data_ptr(coord_0),
                drjit_data_ptr(coord_1),
                drjit_data_ptr(active),
                drjit_data_ptr(task_segment_idx),
                drjit_data_ptr(seg_origin_x),
                drjit_data_ptr(seg_origin_y),
                drjit_data_ptr(seg_origin_z),
                drjit_data_ptr(seg_dir_x),
                drjit_data_ptr(seg_dir_y),
                drjit_data_ptr(seg_dir_z),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(seg_field_re),
                drjit_data_ptr(seg_field_im),
                drjit_data_ptr(seg_vec_x_re),
                drjit_data_ptr(seg_vec_x_im),
                drjit_data_ptr(seg_vec_y_re),
                drjit_data_ptr(seg_vec_y_im),
                drjit_data_ptr(seg_vec_z_re),
                drjit_data_ptr(seg_vec_z_im),
                wavelength,
                k,
                n_rays,
                drjit_data_ptr_mut(out_field_re),
                drjit_data_ptr_mut(out_field_im),
                drjit_data_ptr_mut(out_vec_x_re),
                drjit_data_ptr_mut(out_vec_x_im),
                drjit_data_ptr_mut(out_vec_y_re),
                drjit_data_ptr_mut(out_vec_y_im),
                drjit_data_ptr_mut(out_vec_z_re),
                drjit_data_ptr_mut(out_vec_z_im)
            );

            return nb::make_tuple(
                out_field_re,
                out_field_im,
                out_vec_x_re,
                out_vec_x_im,
                out_vec_y_re,
                out_vec_y_im,
                out_vec_z_re,
                out_vec_z_im
            );
        },
        "Launch reflected suffix grid forward accumulation kernel."
    );

    m.def(
        "suffix_grid_jvp_raw",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            const DiffFloat &coord_0,
            const DiffFloat &coord_1,
            const Int32 &active,
            const Int32 &task_segment_idx,
            const DiffFloat &seg_origin_x,
            const DiffFloat &seg_origin_y,
            const DiffFloat &seg_origin_z,
            const DiffFloat &seg_dir_x,
            const DiffFloat &seg_dir_y,
            const DiffFloat &seg_dir_z,
            const DiffFloat &blocker_dist,
            const DiffFloat &seg_field_re,
            const DiffFloat &seg_field_im,
            const DiffFloat &seg_vec_x_re,
            const DiffFloat &seg_vec_x_im,
            const DiffFloat &seg_vec_y_re,
            const DiffFloat &seg_vec_y_im,
            const DiffFloat &seg_vec_z_re,
            const DiffFloat &seg_vec_z_im,
            const DiffFloat &t_seg_origin_x,
            const DiffFloat &t_seg_origin_y,
            const DiffFloat &t_seg_origin_z,
            const DiffFloat &t_seg_field_re,
            const DiffFloat &t_seg_field_im,
            const DiffFloat &t_seg_vec_x_re,
            const DiffFloat &t_seg_vec_x_im,
            const DiffFloat &t_seg_vec_y_re,
            const DiffFloat &t_seg_vec_y_im,
            const DiffFloat &t_seg_vec_z_re,
            const DiffFloat &t_seg_vec_z_im,
            float wavelength,
            float k,
            int n_rays
        ) {
            size_t n_rx = static_cast<size_t>(n_coord_0) * static_cast<size_t>(n_coord_1);
            DiffFloat out_field_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_field_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_x_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_x_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_y_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_y_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_z_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_z_im = drjit::zeros<DiffFloat>(n_rx);

            drjit::eval(
                coord_0,
                coord_1,
                active,
                task_segment_idx,
                seg_origin_x,
                seg_origin_y,
                seg_origin_z,
                seg_dir_x,
                seg_dir_y,
                seg_dir_z,
                blocker_dist,
                seg_field_re,
                seg_field_im,
                seg_vec_x_re,
                seg_vec_x_im,
                seg_vec_y_re,
                seg_vec_y_im,
                seg_vec_z_re,
                seg_vec_z_im,
                t_seg_origin_x,
                t_seg_origin_y,
                t_seg_origin_z,
                t_seg_field_re,
                t_seg_field_im,
                t_seg_vec_x_re,
                t_seg_vec_x_im,
                t_seg_vec_y_re,
                t_seg_vec_y_im,
                t_seg_vec_z_re,
                t_seg_vec_z_im,
                out_field_re,
                out_field_im,
                out_vec_x_re,
                out_vec_x_im,
                out_vec_y_re,
                out_vec_y_im,
                out_vec_z_re,
                out_vec_z_im
            );

            witwin::channel::native_ext::suffix_grid_jvp(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                drjit_data_ptr(coord_0),
                drjit_data_ptr(coord_1),
                drjit_data_ptr(active),
                drjit_data_ptr(task_segment_idx),
                drjit_data_ptr(seg_origin_x),
                drjit_data_ptr(seg_origin_y),
                drjit_data_ptr(seg_origin_z),
                drjit_data_ptr(seg_dir_x),
                drjit_data_ptr(seg_dir_y),
                drjit_data_ptr(seg_dir_z),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(seg_field_re),
                drjit_data_ptr(seg_field_im),
                drjit_data_ptr(seg_vec_x_re),
                drjit_data_ptr(seg_vec_x_im),
                drjit_data_ptr(seg_vec_y_re),
                drjit_data_ptr(seg_vec_y_im),
                drjit_data_ptr(seg_vec_z_re),
                drjit_data_ptr(seg_vec_z_im),
                drjit_data_ptr(t_seg_origin_x),
                drjit_data_ptr(t_seg_origin_y),
                drjit_data_ptr(t_seg_origin_z),
                drjit_data_ptr(t_seg_field_re),
                drjit_data_ptr(t_seg_field_im),
                drjit_data_ptr(t_seg_vec_x_re),
                drjit_data_ptr(t_seg_vec_x_im),
                drjit_data_ptr(t_seg_vec_y_re),
                drjit_data_ptr(t_seg_vec_y_im),
                drjit_data_ptr(t_seg_vec_z_re),
                drjit_data_ptr(t_seg_vec_z_im),
                wavelength,
                k,
                n_rays,
                drjit_data_ptr_mut(out_field_re),
                drjit_data_ptr_mut(out_field_im),
                drjit_data_ptr_mut(out_vec_x_re),
                drjit_data_ptr_mut(out_vec_x_im),
                drjit_data_ptr_mut(out_vec_y_re),
                drjit_data_ptr_mut(out_vec_y_im),
                drjit_data_ptr_mut(out_vec_z_re),
                drjit_data_ptr_mut(out_vec_z_im)
            );

            return nb::make_tuple(
                out_field_re,
                out_field_im,
                out_vec_x_re,
                out_vec_x_im,
                out_vec_y_re,
                out_vec_y_im,
                out_vec_z_re,
                out_vec_z_im
            );
        },
        "Launch reflected suffix grid JVP kernel."
    );

    m.def(
        "suffix_grid_jvp_resume_raw",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            const DiffFloat &coord_0,
            const DiffFloat &coord_1,
            const Int32 &active,
            const DiffFloat &seg_origin_x,
            const DiffFloat &seg_origin_y,
            const DiffFloat &seg_origin_z,
            const DiffFloat &seg_dir_x,
            const DiffFloat &seg_dir_y,
            const DiffFloat &seg_dir_z,
            const DiffFloat &blocker_dist,
            const DiffFloat &seg_field_re,
            const DiffFloat &seg_field_im,
            const DiffFloat &seg_vec_x_re,
            const DiffFloat &seg_vec_x_im,
            const DiffFloat &seg_vec_y_re,
            const DiffFloat &seg_vec_y_im,
            const DiffFloat &seg_vec_z_re,
            const DiffFloat &seg_vec_z_im,
            const DiffFloat &trace_coord_0,
            const DiffFloat &trace_coord_1,
            const DiffFloat &trace_t,
            const DiffFloat &trace_t_max_0,
            const DiffFloat &trace_t_max_1,
            const DiffFloat &t_seg_origin_x,
            const DiffFloat &t_seg_origin_y,
            const DiffFloat &t_seg_origin_z,
            const DiffFloat &t_seg_field_re,
            const DiffFloat &t_seg_field_im,
            const DiffFloat &t_seg_vec_x_re,
            const DiffFloat &t_seg_vec_x_im,
            const DiffFloat &t_seg_vec_y_re,
            const DiffFloat &t_seg_vec_y_im,
            const DiffFloat &t_seg_vec_z_re,
            const DiffFloat &t_seg_vec_z_im,
            float wavelength,
            float k,
            int n_rays
        ) {
            size_t n_rx = static_cast<size_t>(n_coord_0) * static_cast<size_t>(n_coord_1);
            DiffFloat out_field_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_field_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_x_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_x_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_y_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_y_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_z_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_z_im = drjit::zeros<DiffFloat>(n_rx);

            drjit::eval(
                coord_0,
                coord_1,
                active,
                seg_origin_x,
                seg_origin_y,
                seg_origin_z,
                seg_dir_x,
                seg_dir_y,
                seg_dir_z,
                blocker_dist,
                seg_field_re,
                seg_field_im,
                seg_vec_x_re,
                seg_vec_x_im,
                seg_vec_y_re,
                seg_vec_y_im,
                seg_vec_z_re,
                seg_vec_z_im,
                trace_coord_0,
                trace_coord_1,
                trace_t,
                trace_t_max_0,
                trace_t_max_1,
                t_seg_origin_x,
                t_seg_origin_y,
                t_seg_origin_z,
                t_seg_field_re,
                t_seg_field_im,
                t_seg_vec_x_re,
                t_seg_vec_x_im,
                t_seg_vec_y_re,
                t_seg_vec_y_im,
                t_seg_vec_z_re,
                t_seg_vec_z_im,
                out_field_re,
                out_field_im,
                out_vec_x_re,
                out_vec_x_im,
                out_vec_y_re,
                out_vec_y_im,
                out_vec_z_re,
                out_vec_z_im
            );

            witwin::channel::native_ext::suffix_grid_jvp_resume(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                drjit_data_ptr(coord_0),
                drjit_data_ptr(coord_1),
                drjit_data_ptr(active),
                drjit_data_ptr(seg_origin_x),
                drjit_data_ptr(seg_origin_y),
                drjit_data_ptr(seg_origin_z),
                drjit_data_ptr(seg_dir_x),
                drjit_data_ptr(seg_dir_y),
                drjit_data_ptr(seg_dir_z),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(seg_field_re),
                drjit_data_ptr(seg_field_im),
                drjit_data_ptr(seg_vec_x_re),
                drjit_data_ptr(seg_vec_x_im),
                drjit_data_ptr(seg_vec_y_re),
                drjit_data_ptr(seg_vec_y_im),
                drjit_data_ptr(seg_vec_z_re),
                drjit_data_ptr(seg_vec_z_im),
                drjit_data_ptr(trace_coord_0),
                drjit_data_ptr(trace_coord_1),
                drjit_data_ptr(trace_t),
                drjit_data_ptr(trace_t_max_0),
                drjit_data_ptr(trace_t_max_1),
                drjit_data_ptr(t_seg_origin_x),
                drjit_data_ptr(t_seg_origin_y),
                drjit_data_ptr(t_seg_origin_z),
                drjit_data_ptr(t_seg_field_re),
                drjit_data_ptr(t_seg_field_im),
                drjit_data_ptr(t_seg_vec_x_re),
                drjit_data_ptr(t_seg_vec_x_im),
                drjit_data_ptr(t_seg_vec_y_re),
                drjit_data_ptr(t_seg_vec_y_im),
                drjit_data_ptr(t_seg_vec_z_re),
                drjit_data_ptr(t_seg_vec_z_im),
                wavelength,
                k,
                n_rays,
                drjit_data_ptr_mut(out_field_re),
                drjit_data_ptr_mut(out_field_im),
                drjit_data_ptr_mut(out_vec_x_re),
                drjit_data_ptr_mut(out_vec_x_im),
                drjit_data_ptr_mut(out_vec_y_re),
                drjit_data_ptr_mut(out_vec_y_im),
                drjit_data_ptr_mut(out_vec_z_re),
                drjit_data_ptr_mut(out_vec_z_im)
            );

            return nb::make_tuple(
                out_field_re,
                out_field_im,
                out_vec_x_re,
                out_vec_x_im,
                out_vec_y_re,
                out_vec_y_im,
                out_vec_z_re,
                out_vec_z_im
            );
        },
        "Launch reflected suffix grid resume JVP kernel."
    );

    m.def(
        "suffix_grid_forward_resume_raw",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            const DiffFloat &coord_0,
            const DiffFloat &coord_1,
            const Int32 &active,
            const DiffFloat &seg_origin_x,
            const DiffFloat &seg_origin_y,
            const DiffFloat &seg_origin_z,
            const DiffFloat &seg_dir_x,
            const DiffFloat &seg_dir_y,
            const DiffFloat &seg_dir_z,
            const DiffFloat &blocker_dist,
            const DiffFloat &seg_field_re,
            const DiffFloat &seg_field_im,
            const DiffFloat &seg_vec_x_re,
            const DiffFloat &seg_vec_x_im,
            const DiffFloat &seg_vec_y_re,
            const DiffFloat &seg_vec_y_im,
            const DiffFloat &seg_vec_z_re,
            const DiffFloat &seg_vec_z_im,
            const DiffFloat &trace_coord_0,
            const DiffFloat &trace_coord_1,
            const DiffFloat &trace_t,
            const DiffFloat &trace_t_max_0,
            const DiffFloat &trace_t_max_1,
            float wavelength,
            float k,
            int n_rays
        ) {
            size_t n_rx = static_cast<size_t>(n_coord_0) * static_cast<size_t>(n_coord_1);
            DiffFloat out_field_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_field_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_x_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_x_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_y_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_y_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_z_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_z_im = drjit::zeros<DiffFloat>(n_rx);

            drjit::eval(
                coord_0,
                coord_1,
                active,
                seg_origin_x,
                seg_origin_y,
                seg_origin_z,
                seg_dir_x,
                seg_dir_y,
                seg_dir_z,
                blocker_dist,
                seg_field_re,
                seg_field_im,
                seg_vec_x_re,
                seg_vec_x_im,
                seg_vec_y_re,
                seg_vec_y_im,
                seg_vec_z_re,
                seg_vec_z_im,
                trace_coord_0,
                trace_coord_1,
                trace_t,
                trace_t_max_0,
                trace_t_max_1,
                out_field_re,
                out_field_im,
                out_vec_x_re,
                out_vec_x_im,
                out_vec_y_re,
                out_vec_y_im,
                out_vec_z_re,
                out_vec_z_im
            );

            witwin::channel::native_ext::suffix_grid_forward_resume(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                drjit_data_ptr(coord_0),
                drjit_data_ptr(coord_1),
                drjit_data_ptr(active),
                drjit_data_ptr(seg_origin_x),
                drjit_data_ptr(seg_origin_y),
                drjit_data_ptr(seg_origin_z),
                drjit_data_ptr(seg_dir_x),
                drjit_data_ptr(seg_dir_y),
                drjit_data_ptr(seg_dir_z),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(seg_field_re),
                drjit_data_ptr(seg_field_im),
                drjit_data_ptr(seg_vec_x_re),
                drjit_data_ptr(seg_vec_x_im),
                drjit_data_ptr(seg_vec_y_re),
                drjit_data_ptr(seg_vec_y_im),
                drjit_data_ptr(seg_vec_z_re),
                drjit_data_ptr(seg_vec_z_im),
                drjit_data_ptr(trace_coord_0),
                drjit_data_ptr(trace_coord_1),
                drjit_data_ptr(trace_t),
                drjit_data_ptr(trace_t_max_0),
                drjit_data_ptr(trace_t_max_1),
                wavelength,
                k,
                n_rays,
                drjit_data_ptr_mut(out_field_re),
                drjit_data_ptr_mut(out_field_im),
                drjit_data_ptr_mut(out_vec_x_re),
                drjit_data_ptr_mut(out_vec_x_im),
                drjit_data_ptr_mut(out_vec_y_re),
                drjit_data_ptr_mut(out_vec_y_im),
                drjit_data_ptr_mut(out_vec_z_re),
                drjit_data_ptr_mut(out_vec_z_im)
            );

            return nb::make_tuple(
                out_field_re,
                out_field_im,
                out_vec_x_re,
                out_vec_x_im,
                out_vec_y_re,
                out_vec_y_im,
                out_vec_z_re,
                out_vec_z_im
            );
        },
        "Launch reflected suffix grid forward accumulation kernel from precomputed DDA state."
    );

    m.def(
        "suffix_grid_backward_raw",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            const DiffFloat &coord_0,
            const DiffFloat &coord_1,
            const Int32 &active,
            const Int32 &task_segment_idx,
            const DiffFloat &seg_origin_x,
            const DiffFloat &seg_origin_y,
            const DiffFloat &seg_origin_z,
            const DiffFloat &seg_dir_x,
            const DiffFloat &seg_dir_y,
            const DiffFloat &seg_dir_z,
            const DiffFloat &blocker_dist,
            const DiffFloat &seg_field_re,
            const DiffFloat &seg_field_im,
            const DiffFloat &seg_vec_x_re,
            const DiffFloat &seg_vec_x_im,
            const DiffFloat &seg_vec_y_re,
            const DiffFloat &seg_vec_y_im,
            const DiffFloat &seg_vec_z_re,
            const DiffFloat &seg_vec_z_im,
            float wavelength,
            float k,
            int n_rays,
            const DiffFloat &grad_field_re,
            const DiffFloat &grad_field_im,
            const DiffFloat &grad_vec_x_re,
            const DiffFloat &grad_vec_x_im,
            const DiffFloat &grad_vec_y_re,
            const DiffFloat &grad_vec_y_im,
            const DiffFloat &grad_vec_z_re,
            const DiffFloat &grad_vec_z_im
        ) {
            size_t n_ray = drjit::width(seg_origin_x);
            DiffFloat grad_seg_origin_x = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_origin_y = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_origin_z = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_field_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_field_im = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_x_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_x_im = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_y_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_y_im = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_z_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_z_im = drjit::zeros<DiffFloat>(n_ray);

            drjit::eval(
                coord_0,
                coord_1,
                active,
                task_segment_idx,
                seg_origin_x,
                seg_origin_y,
                seg_origin_z,
                seg_dir_x,
                seg_dir_y,
                seg_dir_z,
                blocker_dist,
                seg_field_re,
                seg_field_im,
                seg_vec_x_re,
                seg_vec_x_im,
                seg_vec_y_re,
                seg_vec_y_im,
                seg_vec_z_re,
                seg_vec_z_im,
                grad_field_re,
                grad_field_im,
                grad_vec_x_re,
                grad_vec_x_im,
                grad_vec_y_re,
                grad_vec_y_im,
                grad_vec_z_re,
                grad_vec_z_im,
                grad_seg_origin_x,
                grad_seg_origin_y,
                grad_seg_origin_z,
                grad_seg_field_re,
                grad_seg_field_im,
                grad_seg_vec_x_re,
                grad_seg_vec_x_im,
                grad_seg_vec_y_re,
                grad_seg_vec_y_im,
                grad_seg_vec_z_re,
                grad_seg_vec_z_im
            );

            witwin::channel::native_ext::suffix_grid_backward(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                drjit_data_ptr(coord_0),
                drjit_data_ptr(coord_1),
                drjit_data_ptr(active),
                drjit_data_ptr(task_segment_idx),
                drjit_data_ptr(seg_origin_x),
                drjit_data_ptr(seg_origin_y),
                drjit_data_ptr(seg_origin_z),
                drjit_data_ptr(seg_dir_x),
                drjit_data_ptr(seg_dir_y),
                drjit_data_ptr(seg_dir_z),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(seg_field_re),
                drjit_data_ptr(seg_field_im),
                drjit_data_ptr(seg_vec_x_re),
                drjit_data_ptr(seg_vec_x_im),
                drjit_data_ptr(seg_vec_y_re),
                drjit_data_ptr(seg_vec_y_im),
                drjit_data_ptr(seg_vec_z_re),
                drjit_data_ptr(seg_vec_z_im),
                wavelength,
                k,
                n_rays,
                drjit_data_ptr(grad_field_re),
                drjit_data_ptr(grad_field_im),
                drjit_data_ptr(grad_vec_x_re),
                drjit_data_ptr(grad_vec_x_im),
                drjit_data_ptr(grad_vec_y_re),
                drjit_data_ptr(grad_vec_y_im),
                drjit_data_ptr(grad_vec_z_re),
                drjit_data_ptr(grad_vec_z_im),
                drjit_data_ptr_mut(grad_seg_origin_x),
                drjit_data_ptr_mut(grad_seg_origin_y),
                drjit_data_ptr_mut(grad_seg_origin_z),
                drjit_data_ptr_mut(grad_seg_field_re),
                drjit_data_ptr_mut(grad_seg_field_im),
                drjit_data_ptr_mut(grad_seg_vec_x_re),
                drjit_data_ptr_mut(grad_seg_vec_x_im),
                drjit_data_ptr_mut(grad_seg_vec_y_re),
                drjit_data_ptr_mut(grad_seg_vec_y_im),
                drjit_data_ptr_mut(grad_seg_vec_z_re),
                drjit_data_ptr_mut(grad_seg_vec_z_im)
            );

            return nb::make_tuple(
                grad_seg_origin_x,
                grad_seg_origin_y,
                grad_seg_origin_z,
                grad_seg_field_re,
                grad_seg_field_im,
                grad_seg_vec_x_re,
                grad_seg_vec_x_im,
                grad_seg_vec_y_re,
                grad_seg_vec_y_im,
                grad_seg_vec_z_re,
                grad_seg_vec_z_im
            );
        },
        "Launch reflected suffix grid backward kernel."
    );

    m.def(
        "suffix_grid_backward_resume_raw",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            const DiffFloat &coord_0,
            const DiffFloat &coord_1,
            const Int32 &active,
            const DiffFloat &seg_origin_x,
            const DiffFloat &seg_origin_y,
            const DiffFloat &seg_origin_z,
            const DiffFloat &seg_dir_x,
            const DiffFloat &seg_dir_y,
            const DiffFloat &seg_dir_z,
            const DiffFloat &blocker_dist,
            const DiffFloat &seg_field_re,
            const DiffFloat &seg_field_im,
            const DiffFloat &seg_vec_x_re,
            const DiffFloat &seg_vec_x_im,
            const DiffFloat &seg_vec_y_re,
            const DiffFloat &seg_vec_y_im,
            const DiffFloat &seg_vec_z_re,
            const DiffFloat &seg_vec_z_im,
            const DiffFloat &trace_coord_0,
            const DiffFloat &trace_coord_1,
            const DiffFloat &trace_t,
            const DiffFloat &trace_t_max_0,
            const DiffFloat &trace_t_max_1,
            float wavelength,
            float k,
            int n_rays,
            const DiffFloat &grad_field_re,
            const DiffFloat &grad_field_im,
            const DiffFloat &grad_vec_x_re,
            const DiffFloat &grad_vec_x_im,
            const DiffFloat &grad_vec_y_re,
            const DiffFloat &grad_vec_y_im,
            const DiffFloat &grad_vec_z_re,
            const DiffFloat &grad_vec_z_im
        ) {
            size_t n_ray = static_cast<size_t>(n_rays);
            DiffFloat grad_seg_origin_x = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_origin_y = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_origin_z = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_field_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_field_im = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_x_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_x_im = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_y_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_y_im = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_z_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_z_im = drjit::zeros<DiffFloat>(n_ray);

            drjit::eval(
                coord_0,
                coord_1,
                active,
                seg_origin_x,
                seg_origin_y,
                seg_origin_z,
                seg_dir_x,
                seg_dir_y,
                seg_dir_z,
                blocker_dist,
                seg_field_re,
                seg_field_im,
                seg_vec_x_re,
                seg_vec_x_im,
                seg_vec_y_re,
                seg_vec_y_im,
                seg_vec_z_re,
                seg_vec_z_im,
                trace_coord_0,
                trace_coord_1,
                trace_t,
                trace_t_max_0,
                trace_t_max_1,
                grad_field_re,
                grad_field_im,
                grad_vec_x_re,
                grad_vec_x_im,
                grad_vec_y_re,
                grad_vec_y_im,
                grad_vec_z_re,
                grad_vec_z_im,
                grad_seg_origin_x,
                grad_seg_origin_y,
                grad_seg_origin_z,
                grad_seg_field_re,
                grad_seg_field_im,
                grad_seg_vec_x_re,
                grad_seg_vec_x_im,
                grad_seg_vec_y_re,
                grad_seg_vec_y_im,
                grad_seg_vec_z_re,
                grad_seg_vec_z_im
            );

            witwin::channel::native_ext::suffix_grid_backward_resume(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                drjit_data_ptr(coord_0),
                drjit_data_ptr(coord_1),
                drjit_data_ptr(active),
                drjit_data_ptr(seg_origin_x),
                drjit_data_ptr(seg_origin_y),
                drjit_data_ptr(seg_origin_z),
                drjit_data_ptr(seg_dir_x),
                drjit_data_ptr(seg_dir_y),
                drjit_data_ptr(seg_dir_z),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(seg_field_re),
                drjit_data_ptr(seg_field_im),
                drjit_data_ptr(seg_vec_x_re),
                drjit_data_ptr(seg_vec_x_im),
                drjit_data_ptr(seg_vec_y_re),
                drjit_data_ptr(seg_vec_y_im),
                drjit_data_ptr(seg_vec_z_re),
                drjit_data_ptr(seg_vec_z_im),
                drjit_data_ptr(trace_coord_0),
                drjit_data_ptr(trace_coord_1),
                drjit_data_ptr(trace_t),
                drjit_data_ptr(trace_t_max_0),
                drjit_data_ptr(trace_t_max_1),
                wavelength,
                k,
                n_rays,
                drjit_data_ptr(grad_field_re),
                drjit_data_ptr(grad_field_im),
                drjit_data_ptr(grad_vec_x_re),
                drjit_data_ptr(grad_vec_x_im),
                drjit_data_ptr(grad_vec_y_re),
                drjit_data_ptr(grad_vec_y_im),
                drjit_data_ptr(grad_vec_z_re),
                drjit_data_ptr(grad_vec_z_im),
                drjit_data_ptr_mut(grad_seg_origin_x),
                drjit_data_ptr_mut(grad_seg_origin_y),
                drjit_data_ptr_mut(grad_seg_origin_z),
                drjit_data_ptr_mut(grad_seg_field_re),
                drjit_data_ptr_mut(grad_seg_field_im),
                drjit_data_ptr_mut(grad_seg_vec_x_re),
                drjit_data_ptr_mut(grad_seg_vec_x_im),
                drjit_data_ptr_mut(grad_seg_vec_y_re),
                drjit_data_ptr_mut(grad_seg_vec_y_im),
                drjit_data_ptr_mut(grad_seg_vec_z_re),
                drjit_data_ptr_mut(grad_seg_vec_z_im)
            );

            return nb::make_tuple(
                grad_seg_origin_x,
                grad_seg_origin_y,
                grad_seg_origin_z,
                grad_seg_field_re,
                grad_seg_field_im,
                grad_seg_vec_x_re,
                grad_seg_vec_x_im,
                grad_seg_vec_y_re,
                grad_seg_vec_y_im,
                grad_seg_vec_z_re,
                grad_seg_vec_z_im
            );
        },
        "Launch reflected suffix grid resume backward kernel."
    );

    m.def(
        "suffix_grid_forward_resume_batched_raw",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            const DiffFloat &coord_0,
            const DiffFloat &coord_1,
            const Int32 &active,
            const Int32 &task_segment_idx,
            const DiffFloat &seg_origin_x,
            const DiffFloat &seg_origin_y,
            const DiffFloat &seg_origin_z,
            const DiffFloat &seg_dir_x,
            const DiffFloat &seg_dir_y,
            const DiffFloat &seg_dir_z,
            const DiffFloat &blocker_dist,
            const DiffFloat &seg_field_re,
            const DiffFloat &seg_field_im,
            const DiffFloat &seg_vec_x_re,
            const DiffFloat &seg_vec_x_im,
            const DiffFloat &seg_vec_y_re,
            const DiffFloat &seg_vec_y_im,
            const DiffFloat &seg_vec_z_re,
            const DiffFloat &seg_vec_z_im,
            const DiffFloat &trace_coord_0,
            const DiffFloat &trace_coord_1,
            const DiffFloat &trace_t,
            const DiffFloat &trace_t_max_0,
            const DiffFloat &trace_t_max_1,
            const Int32 &tile_i0,
            const Int32 &tile_i1,
            const Int32 &tile_extent_0,
            const Int32 &tile_extent_1,
            float wavelength,
            float k,
            int n_rays
        ) {
            size_t n_rx = static_cast<size_t>(n_coord_0) * static_cast<size_t>(n_coord_1);
            DiffFloat out_field_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_field_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_x_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_x_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_y_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_y_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_z_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_z_im = drjit::zeros<DiffFloat>(n_rx);

            drjit::eval(
                coord_0,
                coord_1,
                active,
                task_segment_idx,
                seg_origin_x,
                seg_origin_y,
                seg_origin_z,
                seg_dir_x,
                seg_dir_y,
                seg_dir_z,
                blocker_dist,
                seg_field_re,
                seg_field_im,
                seg_vec_x_re,
                seg_vec_x_im,
                seg_vec_y_re,
                seg_vec_y_im,
                seg_vec_z_re,
                seg_vec_z_im,
                trace_coord_0,
                trace_coord_1,
                trace_t,
                trace_t_max_0,
                trace_t_max_1,
                tile_i0,
                tile_i1,
                tile_extent_0,
                tile_extent_1,
                out_field_re,
                out_field_im,
                out_vec_x_re,
                out_vec_x_im,
                out_vec_y_re,
                out_vec_y_im,
                out_vec_z_re,
                out_vec_z_im
            );

            witwin::channel::native_ext::suffix_grid_forward_resume_batched(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                drjit_data_ptr(coord_0),
                drjit_data_ptr(coord_1),
                drjit_data_ptr(active),
                drjit_data_ptr(task_segment_idx),
                drjit_data_ptr(seg_origin_x),
                drjit_data_ptr(seg_origin_y),
                drjit_data_ptr(seg_origin_z),
                drjit_data_ptr(seg_dir_x),
                drjit_data_ptr(seg_dir_y),
                drjit_data_ptr(seg_dir_z),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(seg_field_re),
                drjit_data_ptr(seg_field_im),
                drjit_data_ptr(seg_vec_x_re),
                drjit_data_ptr(seg_vec_x_im),
                drjit_data_ptr(seg_vec_y_re),
                drjit_data_ptr(seg_vec_y_im),
                drjit_data_ptr(seg_vec_z_re),
                drjit_data_ptr(seg_vec_z_im),
                drjit_data_ptr(trace_coord_0),
                drjit_data_ptr(trace_coord_1),
                drjit_data_ptr(trace_t),
                drjit_data_ptr(trace_t_max_0),
                drjit_data_ptr(trace_t_max_1),
                drjit_data_ptr(tile_i0),
                drjit_data_ptr(tile_i1),
                drjit_data_ptr(tile_extent_0),
                drjit_data_ptr(tile_extent_1),
                wavelength,
                k,
                n_rays,
                drjit_data_ptr_mut(out_field_re),
                drjit_data_ptr_mut(out_field_im),
                drjit_data_ptr_mut(out_vec_x_re),
                drjit_data_ptr_mut(out_vec_x_im),
                drjit_data_ptr_mut(out_vec_y_re),
                drjit_data_ptr_mut(out_vec_y_im),
                drjit_data_ptr_mut(out_vec_z_re),
                drjit_data_ptr_mut(out_vec_z_im)
            );

            return nb::make_tuple(
                out_field_re,
                out_field_im,
                out_vec_x_re,
                out_vec_x_im,
                out_vec_y_re,
                out_vec_y_im,
                out_vec_z_re,
                out_vec_z_im
            );
        },
        "Launch reflected suffix grid batched resume forward kernel."
    );

    m.def(
        "suffix_grid_jvp_resume_batched_raw",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            const DiffFloat &coord_0,
            const DiffFloat &coord_1,
            const Int32 &active,
            const Int32 &task_segment_idx,
            const DiffFloat &seg_origin_x,
            const DiffFloat &seg_origin_y,
            const DiffFloat &seg_origin_z,
            const DiffFloat &seg_dir_x,
            const DiffFloat &seg_dir_y,
            const DiffFloat &seg_dir_z,
            const DiffFloat &blocker_dist,
            const DiffFloat &seg_field_re,
            const DiffFloat &seg_field_im,
            const DiffFloat &seg_vec_x_re,
            const DiffFloat &seg_vec_x_im,
            const DiffFloat &seg_vec_y_re,
            const DiffFloat &seg_vec_y_im,
            const DiffFloat &seg_vec_z_re,
            const DiffFloat &seg_vec_z_im,
            const DiffFloat &trace_coord_0,
            const DiffFloat &trace_coord_1,
            const DiffFloat &trace_t,
            const DiffFloat &trace_t_max_0,
            const DiffFloat &trace_t_max_1,
            const Int32 &tile_i0,
            const Int32 &tile_i1,
            const Int32 &tile_extent_0,
            const Int32 &tile_extent_1,
            const DiffFloat &t_seg_origin_x,
            const DiffFloat &t_seg_origin_y,
            const DiffFloat &t_seg_origin_z,
            const DiffFloat &t_seg_field_re,
            const DiffFloat &t_seg_field_im,
            const DiffFloat &t_seg_vec_x_re,
            const DiffFloat &t_seg_vec_x_im,
            const DiffFloat &t_seg_vec_y_re,
            const DiffFloat &t_seg_vec_y_im,
            const DiffFloat &t_seg_vec_z_re,
            const DiffFloat &t_seg_vec_z_im,
            float wavelength,
            float k,
            int n_rays
        ) {
            size_t n_rx = static_cast<size_t>(n_coord_0) * static_cast<size_t>(n_coord_1);
            DiffFloat out_field_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_field_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_x_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_x_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_y_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_y_im = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_z_re = drjit::zeros<DiffFloat>(n_rx);
            DiffFloat out_vec_z_im = drjit::zeros<DiffFloat>(n_rx);

            drjit::eval(
                coord_0,
                coord_1,
                active,
                task_segment_idx,
                seg_origin_x,
                seg_origin_y,
                seg_origin_z,
                seg_dir_x,
                seg_dir_y,
                seg_dir_z,
                blocker_dist,
                seg_field_re,
                seg_field_im,
                seg_vec_x_re,
                seg_vec_x_im,
                seg_vec_y_re,
                seg_vec_y_im,
                seg_vec_z_re,
                seg_vec_z_im,
                trace_coord_0,
                trace_coord_1,
                trace_t,
                trace_t_max_0,
                trace_t_max_1,
                tile_i0,
                tile_i1,
                tile_extent_0,
                tile_extent_1,
                t_seg_origin_x,
                t_seg_origin_y,
                t_seg_origin_z,
                t_seg_field_re,
                t_seg_field_im,
                t_seg_vec_x_re,
                t_seg_vec_x_im,
                t_seg_vec_y_re,
                t_seg_vec_y_im,
                t_seg_vec_z_re,
                t_seg_vec_z_im,
                out_field_re,
                out_field_im,
                out_vec_x_re,
                out_vec_x_im,
                out_vec_y_re,
                out_vec_y_im,
                out_vec_z_re,
                out_vec_z_im
            );

            witwin::channel::native_ext::suffix_grid_jvp_resume_batched(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                drjit_data_ptr(coord_0),
                drjit_data_ptr(coord_1),
                drjit_data_ptr(active),
                drjit_data_ptr(task_segment_idx),
                drjit_data_ptr(seg_origin_x),
                drjit_data_ptr(seg_origin_y),
                drjit_data_ptr(seg_origin_z),
                drjit_data_ptr(seg_dir_x),
                drjit_data_ptr(seg_dir_y),
                drjit_data_ptr(seg_dir_z),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(seg_field_re),
                drjit_data_ptr(seg_field_im),
                drjit_data_ptr(seg_vec_x_re),
                drjit_data_ptr(seg_vec_x_im),
                drjit_data_ptr(seg_vec_y_re),
                drjit_data_ptr(seg_vec_y_im),
                drjit_data_ptr(seg_vec_z_re),
                drjit_data_ptr(seg_vec_z_im),
                drjit_data_ptr(trace_coord_0),
                drjit_data_ptr(trace_coord_1),
                drjit_data_ptr(trace_t),
                drjit_data_ptr(trace_t_max_0),
                drjit_data_ptr(trace_t_max_1),
                drjit_data_ptr(tile_i0),
                drjit_data_ptr(tile_i1),
                drjit_data_ptr(tile_extent_0),
                drjit_data_ptr(tile_extent_1),
                drjit_data_ptr(t_seg_origin_x),
                drjit_data_ptr(t_seg_origin_y),
                drjit_data_ptr(t_seg_origin_z),
                drjit_data_ptr(t_seg_field_re),
                drjit_data_ptr(t_seg_field_im),
                drjit_data_ptr(t_seg_vec_x_re),
                drjit_data_ptr(t_seg_vec_x_im),
                drjit_data_ptr(t_seg_vec_y_re),
                drjit_data_ptr(t_seg_vec_y_im),
                drjit_data_ptr(t_seg_vec_z_re),
                drjit_data_ptr(t_seg_vec_z_im),
                wavelength,
                k,
                n_rays,
                drjit_data_ptr_mut(out_field_re),
                drjit_data_ptr_mut(out_field_im),
                drjit_data_ptr_mut(out_vec_x_re),
                drjit_data_ptr_mut(out_vec_x_im),
                drjit_data_ptr_mut(out_vec_y_re),
                drjit_data_ptr_mut(out_vec_y_im),
                drjit_data_ptr_mut(out_vec_z_re),
                drjit_data_ptr_mut(out_vec_z_im)
            );

            return nb::make_tuple(
                out_field_re,
                out_field_im,
                out_vec_x_re,
                out_vec_x_im,
                out_vec_y_re,
                out_vec_y_im,
                out_vec_z_re,
                out_vec_z_im
            );
        },
        "Launch reflected suffix grid batched resume JVP kernel."
    );

    m.def(
        "suffix_grid_backward_resume_batched_raw",
        [](
            int plane_axis,
            float plane_position,
            float coord_0_min,
            float coord_0_max,
            float coord_1_min,
            float coord_1_max,
            float cell_size_0,
            float cell_size_1,
            int n_coord_0,
            int n_coord_1,
            int max_steps,
            const DiffFloat &coord_0,
            const DiffFloat &coord_1,
            const Int32 &active,
            const Int32 &task_segment_idx,
            const DiffFloat &seg_origin_x,
            const DiffFloat &seg_origin_y,
            const DiffFloat &seg_origin_z,
            const DiffFloat &seg_dir_x,
            const DiffFloat &seg_dir_y,
            const DiffFloat &seg_dir_z,
            const DiffFloat &blocker_dist,
            const DiffFloat &seg_field_re,
            const DiffFloat &seg_field_im,
            const DiffFloat &seg_vec_x_re,
            const DiffFloat &seg_vec_x_im,
            const DiffFloat &seg_vec_y_re,
            const DiffFloat &seg_vec_y_im,
            const DiffFloat &seg_vec_z_re,
            const DiffFloat &seg_vec_z_im,
            const DiffFloat &trace_coord_0,
            const DiffFloat &trace_coord_1,
            const DiffFloat &trace_t,
            const DiffFloat &trace_t_max_0,
            const DiffFloat &trace_t_max_1,
            const Int32 &tile_i0,
            const Int32 &tile_i1,
            const Int32 &tile_extent_0,
            const Int32 &tile_extent_1,
            float wavelength,
            float k,
            int n_rays,
            const DiffFloat &grad_field_re,
            const DiffFloat &grad_field_im,
            const DiffFloat &grad_vec_x_re,
            const DiffFloat &grad_vec_x_im,
            const DiffFloat &grad_vec_y_re,
            const DiffFloat &grad_vec_y_im,
            const DiffFloat &grad_vec_z_re,
            const DiffFloat &grad_vec_z_im
        ) {
            size_t n_ray = drjit::width(seg_origin_x);
            DiffFloat grad_seg_origin_x = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_origin_y = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_origin_z = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_field_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_field_im = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_x_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_x_im = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_y_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_y_im = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_z_re = drjit::zeros<DiffFloat>(n_ray);
            DiffFloat grad_seg_vec_z_im = drjit::zeros<DiffFloat>(n_ray);

            drjit::eval(
                coord_0,
                coord_1,
                active,
                task_segment_idx,
                seg_origin_x,
                seg_origin_y,
                seg_origin_z,
                seg_dir_x,
                seg_dir_y,
                seg_dir_z,
                blocker_dist,
                seg_field_re,
                seg_field_im,
                seg_vec_x_re,
                seg_vec_x_im,
                seg_vec_y_re,
                seg_vec_y_im,
                seg_vec_z_re,
                seg_vec_z_im,
                trace_coord_0,
                trace_coord_1,
                trace_t,
                trace_t_max_0,
                trace_t_max_1,
                tile_i0,
                tile_i1,
                tile_extent_0,
                tile_extent_1,
                grad_field_re,
                grad_field_im,
                grad_vec_x_re,
                grad_vec_x_im,
                grad_vec_y_re,
                grad_vec_y_im,
                grad_vec_z_re,
                grad_vec_z_im,
                grad_seg_origin_x,
                grad_seg_origin_y,
                grad_seg_origin_z,
                grad_seg_field_re,
                grad_seg_field_im,
                grad_seg_vec_x_re,
                grad_seg_vec_x_im,
                grad_seg_vec_y_re,
                grad_seg_vec_y_im,
                grad_seg_vec_z_re,
                grad_seg_vec_z_im
            );

            witwin::channel::native_ext::suffix_grid_backward_resume_batched(
                plane_axis,
                plane_position,
                coord_0_min,
                coord_0_max,
                coord_1_min,
                coord_1_max,
                cell_size_0,
                cell_size_1,
                n_coord_0,
                n_coord_1,
                max_steps,
                drjit_data_ptr(coord_0),
                drjit_data_ptr(coord_1),
                drjit_data_ptr(active),
                drjit_data_ptr(task_segment_idx),
                drjit_data_ptr(seg_origin_x),
                drjit_data_ptr(seg_origin_y),
                drjit_data_ptr(seg_origin_z),
                drjit_data_ptr(seg_dir_x),
                drjit_data_ptr(seg_dir_y),
                drjit_data_ptr(seg_dir_z),
                drjit_data_ptr(blocker_dist),
                drjit_data_ptr(seg_field_re),
                drjit_data_ptr(seg_field_im),
                drjit_data_ptr(seg_vec_x_re),
                drjit_data_ptr(seg_vec_x_im),
                drjit_data_ptr(seg_vec_y_re),
                drjit_data_ptr(seg_vec_y_im),
                drjit_data_ptr(seg_vec_z_re),
                drjit_data_ptr(seg_vec_z_im),
                drjit_data_ptr(trace_coord_0),
                drjit_data_ptr(trace_coord_1),
                drjit_data_ptr(trace_t),
                drjit_data_ptr(trace_t_max_0),
                drjit_data_ptr(trace_t_max_1),
                drjit_data_ptr(tile_i0),
                drjit_data_ptr(tile_i1),
                drjit_data_ptr(tile_extent_0),
                drjit_data_ptr(tile_extent_1),
                wavelength,
                k,
                n_rays,
                drjit_data_ptr(grad_field_re),
                drjit_data_ptr(grad_field_im),
                drjit_data_ptr(grad_vec_x_re),
                drjit_data_ptr(grad_vec_x_im),
                drjit_data_ptr(grad_vec_y_re),
                drjit_data_ptr(grad_vec_y_im),
                drjit_data_ptr(grad_vec_z_re),
                drjit_data_ptr(grad_vec_z_im),
                drjit_data_ptr_mut(grad_seg_origin_x),
                drjit_data_ptr_mut(grad_seg_origin_y),
                drjit_data_ptr_mut(grad_seg_origin_z),
                drjit_data_ptr_mut(grad_seg_field_re),
                drjit_data_ptr_mut(grad_seg_field_im),
                drjit_data_ptr_mut(grad_seg_vec_x_re),
                drjit_data_ptr_mut(grad_seg_vec_x_im),
                drjit_data_ptr_mut(grad_seg_vec_y_re),
                drjit_data_ptr_mut(grad_seg_vec_y_im),
                drjit_data_ptr_mut(grad_seg_vec_z_re),
                drjit_data_ptr_mut(grad_seg_vec_z_im)
            );

            return nb::make_tuple(
                grad_seg_origin_x,
                grad_seg_origin_y,
                grad_seg_origin_z,
                grad_seg_field_re,
                grad_seg_field_im,
                grad_seg_vec_x_re,
                grad_seg_vec_x_im,
                grad_seg_vec_y_re,
                grad_seg_vec_y_im,
                grad_seg_vec_z_re,
                grad_seg_vec_z_im
            );
        },
        "Launch reflected suffix grid batched resume backward kernel."
    );
}
